import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static const supportedLocales = [
    Locale('en'),
    Locale('hi'),
  ];

  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates = [
    _AppLocalizationsDelegate(),
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ];

  static AppLocalizations of(BuildContext context) {
    final localizations = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    return localizations ?? AppLocalizations(const Locale('en'));
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'App Language': 'App Language',
      'Choose Language': 'Choose Language',
      'English': 'English',
      'Hindi': 'Hindi',
      'Language': 'Language',
      'Volunteer': 'Volunteer',
      'Hi, {name}!': 'Hi, {name}!',
      'Find your next volunteer event': 'Find your next volunteer event',
      'My Ongoing Events': 'My Ongoing Events',
      'My Upcoming Events': 'My Upcoming Events',
      'Upcoming': 'Upcoming',
      'Ongoing': 'Ongoing',
      'No ongoing events yet': 'No ongoing events yet',
      'No upcoming events yet': 'No upcoming events yet',
      'View All': 'View All',
      'Recommended for You': 'Recommended for You',
      'No recommendations available': 'No recommendations available',
      'Event details not available': 'Event details not available',
      'Failed to open event details': 'Failed to open event details',
      'Pending Rating Reminder': 'Pending Rating Reminder',
      'Share your feedback for {event}.': 'Share your feedback for {event}.',
      '{count} completed events are waiting for your rating.':
          '{count} completed events are waiting for your rating.',
      'Rate now': 'Rate now',
      'View Details': 'View Details',
      '{filled}/{required} approved': '{filled}/{required} approved',
      'Pending': 'Pending',
      'Approved': 'Approved',
      'Rejected': 'Rejected',
      'Review Closed': 'Review Closed',
      'Cancelled': 'Cancelled',
      'Apply': 'Apply',
      'Home': 'Home',
      'Events': 'Events',
      'Leaderboard': 'Leaderboard',
      'Profile': 'Profile',
      'event': 'event',
      'Failed to load events. Pull to refresh or tap Retry.':
          'Failed to load events. Pull to refresh or tap Retry.',
      'Your verification is under review. You can create events after approval.':
          'Your verification is under review. You can create events after approval.',
      'Your verification was rejected. Please submit verification again to create events.':
          'Your verification was rejected. Please submit verification again to create events.',
      'You need to be verified before creating events.':
          'You need to be verified before creating events.',
      'Unable to verify your account right now. Please try again.':
          'Unable to verify your account right now. Please try again.',
      'Create Event': 'Create Event',
      'All': 'All',
      'Completed': 'Completed',
      'Draft': 'Draft',
      'Retry': 'Retry',
      'All Events': 'All Events',
      'Ongoing Events': 'Ongoing Events',
      'Upcoming Events': 'Upcoming Events',
      'Completed Events': 'Completed Events',
      'Draft Events': 'Draft Events',
      'Cancelled Events': 'Cancelled Events',
      'No {title}': 'No {title}',
      'Organiser: {name}': 'Organiser: {name}',
      'Untitled': 'Untitled',
      'Location: {location}': 'Location: {location}',
      'N/A': 'N/A',
      'Date: {date}': 'Date: {date}',
      'No ratings yet': 'No ratings yet',
      'Review': 'Review',
      'Removed by admin': 'Removed by admin',
      'Not published': 'Not published',
      'Cancelled by organiser': 'Cancelled by organiser',
      'Starts today': 'Starts today',
      'Starts in {days}d': 'Starts in {days}d',
      'Deadline passed': 'Deadline passed',
      'Deadline soon': 'Deadline soon',
      'Approved: {accepted} / {required}': 'Approved: {accepted} / {required}',
      'Applicants: {raw} / {required}': 'Applicants: {raw} / {required}',
      'Draft not visible to volunteers': 'Draft not visible to volunteers',
      'Application deadline passed': 'Application deadline passed',
      'No applications yet': 'No applications yet',
      'Understaffed by {count}': 'Understaffed by {count}',
      'to': 'to',
      'Help & Support': 'Help & Support',
      'FAQs': 'FAQs',
      'Common questions answered': 'Common questions answered',
      'App Support': 'App Support',
      'Issues with the app or login': 'Issues with the app or login',
      'App not loading events?': 'App not loading events?',
      'Check your internet connection and try again.':
          'Check your internet connection and try again.',
      'Login issues?': 'Login issues?',
      'Make sure your credentials are correct or use Forgot Password.':
          'Make sure your credentials are correct or use Forgot Password.',
      'App crashes or bugs?': 'App crashes or bugs?',
      'Restart the app or update to the latest version.':
          'Restart the app or update to the latest version.',
      'Still facing issues?': 'Still facing issues?',
      'Contact our support team via email.':
          'Contact our support team via email.',
      'Safety & Guidelines': 'Safety & Guidelines',
      'Your safety matters': 'Your safety matters',
      'Always verify event details before attending.':
          'Always verify event details before attending.',
      'Avoid sharing personal or financial information.':
          'Avoid sharing personal or financial information.',
      'Report suspicious organisers or events immediately.':
          'Report suspicious organisers or events immediately.',
      'Follow community guidelines and event instructions.':
          'Follow community guidelines and event instructions.',
      'Contact Us': 'Contact Us',
      'Get in touch with our team': 'Get in touch with our team',
      'Contact VolunteerX': 'Contact VolunteerX',
      'Email Support': 'Email Support',
      'Our team usually responds within 24-48 hours.':
          'Our team usually responds within 24-48 hours.',
      'Please include screenshots or details for faster support.':
          'Please include screenshots or details for faster support.',
      'Frequently Asked Questions': 'Frequently Asked Questions',
      'What is the strike/suspension policy?':
          'What is the strike/suspension policy?',
      'Repeated violations may lead to strikes. 2 strikes: 3-day suspension, 3 strikes: 7-day suspension, 4 strikes: account ban.':
          'Repeated violations may lead to strikes. 2 strikes: 3-day suspension, 3 strikes: 7-day suspension, 4 strikes: account ban.',
      'How do I apply for an event?': 'How do I apply for an event?',
      'Open an event card and tap Apply. Fill required details and submit your application.':
          'Open an event card and tap Apply. Fill required details and submit your application.',
      'Can I cancel my application?': 'Can I cancel my application?',
      'Yes. If cancellation is available for that event, you can cancel from your application details.':
          'Yes. If cancellation is available for that event, you can cancel from your application details.',
      'How are badges earned?': 'How are badges earned?',
      'Badges are awarded based on completed events and consistent participation.':
          'Badges are awarded based on completed events and consistent participation.',
      'How do paid event payments work?': 'How do paid event payments work?',
      'Payment status depends on organiser confirmation and event completion.':
          'Payment status depends on organiser confirmation and event completion.',
      'Why are events not loading?': 'Why are events not loading?',
      'Check your internet connection, then refresh the page. If it persists, contact support.':
          'Check your internet connection, then refresh the page. If it persists, contact support.',
      'What if I face login issues?': 'What if I face login issues?',
      'Verify your credentials and try Forgot Password if needed.':
          'Verify your credentials and try Forgot Password if needed.',
      'How can I improve my profile completion?':
          'How can I improve my profile completion?',
      'Update your name, email, city, profile photo, and verification status in profile settings.':
          'Update your name, email, city, profile photo, and verification status in profile settings.',
      'How do I contact support?': 'How do I contact support?',
      'Email volunteerxteam@gmail.com with screenshots and issue details for faster support.':
          'Email volunteerxteam@gmail.com with screenshots and issue details for faster support.',
      'Token not found. Please login again.':
          'Token not found. Please login again.',
      'Error {statusCode}: {message}': 'Error {statusCode}: {message}',
      'Error: {error}': 'Error: {error}',
      'Name': 'Name',
      'Email': 'Email',
      'City': 'City',
      'Profile photo': 'Profile photo',
      'Verification status': 'Verification status',
      'Logout': 'Logout',
      'Are you sure you want to logout?':
          'Are you sure you want to logout?',
      'Cancel': 'Cancel',
      'Delete Account': 'Delete Account',
      'Are you sure you want to delete your account? This action is irreversible.':
          'Are you sure you want to delete your account? This action is irreversible.',
      'Delete': 'Delete',
      'Account deleted successfully.': 'Account deleted successfully.',
      'Delete failed': 'Delete failed',
      'Server error: {error}': 'Server error: {error}',
      'City not set': 'City not set',
      'India': 'India',
      'Edit Profile': 'Edit Profile',
      'Profile Completeness': 'Profile Completeness',
      '{percent}% complete': '{percent}% complete',
      'Missing: {items}': 'Missing: {items}',
      'Impact Summary': 'Impact Summary',
      'Rating': 'Rating',
      'My Applications': 'My Applications',
      'Saved Events': 'Saved Events',
      'My Badges': 'My Badges',
      'Verification Under Review': 'Verification Under Review',
      'Verified': 'Verified',
      'Get Verified': 'Get Verified',
      'Your account is already verified.': 'Your account is already verified.',
      'Your verification request is under review.':
          'Your verification request is under review.',
      'Payment Status': 'Payment Status',
      'Invite Friends': 'Invite Friends',
      'Edit': 'Edit',
      'Only JPG, JPEG, PNG, and WEBP images are allowed':
          'Only JPG, JPEG, PNG, and WEBP images are allowed',
      'Image must be 5 MB or smaller': 'Image must be 5 MB or smaller',
      'Error picking image: {error}': 'Error picking image: {error}',
      'Profile picture updated successfully':
          'Profile picture updated successfully',
      'Failed to upload image': 'Failed to upload image',
      'Remove Profile Picture': 'Remove Profile Picture',
      'Are you sure you want to remove your profile picture?':
          'Are you sure you want to remove your profile picture?',
      'Remove': 'Remove',
      'Profile picture removed successfully':
          'Profile picture removed successfully',
      'Failed to remove picture': 'Failed to remove picture',
      'Name cannot be empty': 'Name cannot be empty',
      'Profile updated, but preferences failed':
          'Profile updated, but preferences failed',
      'Profile updated successfully': 'Profile updated successfully',
      'Update failed: {message}': 'Update failed: {message}',
      'Change Profile Picture': 'Change Profile Picture',
      'Full Name': 'Full Name',
      'City (Optional)': 'City (Optional)',
      'Contact Number (Optional)': 'Contact Number (Optional)',
      'Skills': 'Skills',
      'Add skill': 'Add skill',
      'Interests': 'Interests',
      'Add interest': 'Add interest',
      'Saving...': 'Saving...',
      'Save Changes': 'Save Changes',
      'No items added': 'No items added',
      'Unable to load badges right now.':
          'Unable to load badges right now.',
      'hosted events': 'hosted events',
      'completed events': 'completed events',
      'Requires {threshold} {noun}': 'Requires {threshold} {noun}',
      'Hosted events': 'Hosted events',
      'Completed events': 'Completed events',
      'No badge yet': 'No badge yet',
      'Refresh': 'Refresh',
      'Current Badge: {badge}': 'Current Badge: {badge}',
      '{label}: {count}': '{label}: {count}',
      'Next badge: {name} at {threshold} {label}':
          'Next badge: {name} at {threshold} {label}',
      'No badges configured in system yet.':
          'No badges configured in system yet.',
      'Badge': 'Badge',
      'Status updated': 'Status updated',
      'Failed: {message}': 'Failed: {message}',
      'Failed to update status': 'Failed to update status',
      'Received': 'Received',
      'Not applicable': 'Not applicable',
      'Payment report details are not available.':
          'Payment report details are not available.',
      'This unpaid payment report was already submitted.':
          'This unpaid payment report was already submitted.',
      'Report Unpaid Payment': 'Report Unpaid Payment',
      'This will create an admin report for unpaid compensation on {event}.':
          'This will create an admin report for unpaid compensation on {event}.',
      'this event': 'this event',
      'Details': 'Details',
      'Add any payment issue details for admin review.':
          'Add any payment issue details for admin review.',
      'Please add a short note for admin review.':
          'Please add a short note for admin review.',
      'Submit Report': 'Submit Report',
      'Unknown event': 'Unknown event',
      'Paid event': 'Paid event',
      'Unpaid payment report submitted for admin review.':
          'Unpaid payment report submitted for admin review.',
      'Failed to submit report: {error}':
          'Failed to submit report: {error}',
      'No approved events yet': 'No approved events yet',
      'Unknown Event': 'Unknown Event',
      'Unpaid payment report submitted.': 'Unpaid payment report submitted.',
      'Payment is still pending after clearance date.':
          'Payment is still pending after clearance date.',
      'Reported': 'Reported',
      'Report unpaid payment': 'Report unpaid payment',
      'Please login again to view organiser details.':
          'Please login again to view organiser details.',
      'Failed to load organiser profile': 'Failed to load organiser profile',
      'Network error': 'Network error',
      'Organiser': 'Organiser',
      'Organiser Profile': 'Organiser Profile',
      'About Organisation': 'About Organisation',
      'No description provided by organiser.':
          'No description provided by organiser.',
      'Based in {city}.': 'Based in {city}.',
      'Volunteers': 'Volunteers',
      'Connect with Us': 'Connect with Us',
      'Follow or visit to learn more about their work':
          'Follow or visit to learn more about their work',
      'Website': 'Website',
      'Instagram': 'Instagram',
      'Facebook': 'Facebook',
      'LinkedIn': 'LinkedIn',
      'Phone number is available only to approved volunteers when the organiser enables sharing.':
          'Phone number is available only to approved volunteers when the organiser enables sharing.',
      'Volunteer Reviews': 'Volunteer Reviews',
      'No reviews yet': 'No reviews yet',
      'Anonymous': 'Anonymous',
      'View All {count} Reviews': 'View All {count} Reviews',
      'All Reviews': 'All Reviews',
      'Last 5 Events Overall Rating': 'Last 5 Events Overall Rating',
      'Unknown': 'Unknown',
      'Individual Reviews': 'Individual Reviews',
      '{count} reviews': '{count} reviews',
      'No leaderboard data available': 'No leaderboard data available',
      'Failed to load leaderboard': 'Failed to load leaderboard',
      'Organisers': 'Organisers',
      'Weekly': 'Weekly',
      'Monthly': 'Monthly',
      '{count} events': '{count} events',
      '{count} events completed': '{count} events completed',
      'Announcements': 'Announcements',
      'Failed to load announcements\n{error}':
          'Failed to load announcements\n{error}',
      'No announcements for {event}': 'No announcements for {event}',
      'Announcement': 'Announcement',
      'Please login again': 'Please login again',
      'Please upload ID proof': 'Please upload ID proof',
      'Please upload selfie with ID': 'Please upload selfie with ID',
      'Verification request submitted': 'Verification request submitted',
      'Submission failed': 'Submission failed',
      'You do not need to submit verification again.':
          'You do not need to submit verification again.',
      'Back to Profile': 'Back to Profile',
      'You cannot submit another request until the current one is reviewed.':
          'You cannot submit another request until the current one is reviewed.',
      'Your previous verification request was rejected. Please review your details and submit again.':
          'Your previous verification request was rejected. Please review your details and submit again.',
      'Volunteer Verification': 'Volunteer Verification',
      'ID Type': 'ID Type',
      'Please select ID type': 'Please select ID type',
      'Upload ID Proof *': 'Upload ID Proof *',
      'ID Selected': 'ID Selected',
      'File too large (max 5MB)': 'File too large (max 5MB)',
      'Uploading ID proof...': 'Uploading ID proof...',
      'ID proof uploaded': 'ID proof uploaded',
      'Upload failed: {error}': 'Upload failed: {error}',
      'Upload Selfie with ID *': 'Upload Selfie with ID *',
      'Selfie Selected': 'Selfie Selected',
      'Uploading selfie...': 'Uploading selfie...',
      'Selfie uploaded': 'Selfie uploaded',
      'ID Number': 'ID Number',
      'Enter ID number': 'Enter ID number',
      'Invalid ID number': 'Invalid ID number',
      'Submit for Verification': 'Submit for Verification',
      'Invite friends to VolunteerX': 'Invite friends to VolunteerX',
      'Volunteer together, earn badges faster!':
          'Volunteer together, earn badges faster!',
      'Share Invite Link': 'Share Invite Link',
      'Removed': 'Removed',
      'Date not set': 'Date not set',
      'Your Organisation': 'Your Organisation',
      'Reviews': 'Reviews',
      'Your volunteers will appear here':
          'Your volunteers will appear here',
      'No events found': 'No events found',
      'Untitled Event': 'Untitled Event',
      'Location not set': 'Location not set',
      'Your organisation rating': 'Your organisation rating',
      'Volunteer reviews will appear here':
          'Volunteer reviews will appear here',
      'My Events': 'My Events',
      'Total': 'Total',
      'Search events...': 'Search events...',
            'About Volunteerx': 'About Volunteerx',
            'Account deactivated': 'Account deactivated',
            'Account Settings': 'Account Settings',
            'App Information': 'App Information',
            'App Version': 'App Version',
            'Close': 'Close',
            'Contact Support': 'Contact Support',
            'Deactivate': 'Deactivate',
            'Deactivate Account': 'Deactivate Account',
            'Deactivate failed': 'Deactivate failed',
            'Email our support team': 'Email our support team',
            'Find answers to common questions': 'Find answers to common questions',
            'How can we help you?': 'How can we help you?',
            'OK': 'OK',
            'Organisation Activity': 'Organisation Activity',
            'Report a Problem': 'Report a Problem',
            'Support Email': 'Support Email',
              'Tell us if something isn\'t working':
                  'Tell us if something isn\'t working',
            'Volunteer Details': 'Volunteer Details',
            'Volunteerx Team': 'Volunteerx Team',
      '99+': '99+',
      'Aadhaar': 'Aadhaar',
      'About VolunteerX': 'About VolunteerX',
      'Absent': 'Absent',
      'Add responsibility': 'Add responsibility',
      'Added to shortlist': 'Added to shortlist',
      'Shortlist is closed for this event.':
          'Shortlist is closed for this event.',
      'Announce': 'Announce',
      'Announcement sent. No volunteers to notify yet.': 'Announcement sent. No volunteers to notify yet.',
      'Application Deadline': 'Application Deadline',
      'Applied': 'Applied',
      'Attendance': 'Attendance',
      'Attendance saved': 'Attendance saved',
      'Available': 'Available',
      'Back': 'Back',
      'Badges': 'Badges',
      'Basic Details': 'Basic Details',
      'Cancel Event': 'Cancel Event',
      'Cancelled by organiser/admin': 'Cancelled by organiser/admin',
      'Cancelled by volunteer': 'Cancelled by volunteer',
      'Cannot approve. Slots are full.': 'Cannot approve. Slots are full.',
      'Categories': 'Categories',
      'Category': 'Category',
      'Change Password': 'Change Password',
      'Chat': 'Chat',
      'Chat info not available': 'Chat info not available',
      'Confirm': 'Confirm',
      'Confirm cancellation': 'Confirm cancellation',
      'Please review details before cancelling this event.':
          'Please review details before cancelling this event.',
      'Event: {title}': 'Event: {title}',
      'Reason: {reason}': 'Reason: {reason}',
      'Confirm New Password': 'Confirm New Password',
      'Contact Number': 'Contact Number',
      'Copyright 2026 VolunteerX. All rights reserved.': 'Copyright 2026 VolunteerX. All rights reserved.',
      'Create and manage events': 'Create and manage events',
      'Current Email': 'Current Email',
      'Current Password': 'Current Password',
      'Daily Schedules': 'Daily Schedules',
      'Description': 'Description',
      'Description is required': 'Description is required',
      'Developed By': 'Developed By',
      'Do you want to publish this draft event now?': 'Do you want to publish this draft event now?',
      'Draft saved': 'Draft saved',
      'Edit Draft': 'Edit Draft',
      'Edit Event': 'Edit Event',
      'End Date': 'End Date',
      'End Time': 'End Time',
      'Enter a valid 6-digit OTP': 'Enter a valid 6-digit OTP',
      'Enter a valid email': 'Enter a valid email',
      'Enter a valid phone number': 'Enter a valid phone number',
      'Enter new email address': 'Enter new email address',
      'Enter new password': 'Enter new password',
      'Enter organisation name': 'Enter organisation name',
      'Enter OTP': 'Enter OTP',
      'Enter phone number': 'Enter phone number',
      'Enter valid payment amount': 'Enter valid payment amount',
      'Enter valid volunteers required': 'Enter valid volunteers required',
      'Enter your password': 'Enter your password',
      'Event': 'Event',
      'Event Banner (Optional)': 'Event Banner (Optional)',
      'Event Cancelled': 'Event Cancelled',
      'Event cancelled successfully': 'Event cancelled successfully',
      'Event Chat': 'Event Chat',
      'Event Completed': 'Event Completed',
      'Event created': 'Event created',
      'Event Details': 'Event Details',
      'Event Info': 'Event Info',
      'Event Overview': 'Event Overview',
      'Event published': 'Event published',
      'Event published successfully': 'Event published successfully',
      'Event Title': 'Event Title',
      'Event title is required': 'Event title is required',
      'Event Type': 'Event Type',
      'Event updated': 'Event updated',
      'Event Updates': 'Event Updates',
      'Failed to create event': 'Failed to create event',
      'Failed to load applications. Please try again.': 'Failed to load applications. Please try again.',
      'Failed to load events': 'Failed to load events',
      'Failed to open chat': 'Failed to open chat',
      'Failed to save draft': 'Failed to save draft',
      'Failed to update application status.': 'Failed to update application status.',
      'Field cannot be empty': 'Field cannot be empty',
      'Fixed Amount': 'Fixed Amount',
      'Generate schedules from dates': 'Generate schedules from dates',
      'Government ID (Optional)': 'Government ID (Optional)',
      'Hire trusted volunteers': 'Hire trusted volunteers',
      'Invalid event id': 'Invalid event id',
      'Location': 'Location',
      'Location is required': 'Location is required',
      'Message is required': 'Message is required',
      'Name A-Z': 'Name A-Z',
      'New Email': 'New Email',
      'New Password': 'New Password',
      'New Volunteer Applications': 'New Volunteer Applications',
      'Newest': 'Newest',
      'No approved applications yet': 'No approved applications yet',
      'No badges yet': 'No badges yet',
      'No cancelled applications yet': 'No cancelled applications yet',
      'No pending applications yet': 'No pending applications yet',
      'No recent participation yet.': 'No recent participation yet.',
      'No rejected applications yet': 'No rejected applications yet',
      'No responsibilities added': 'No responsibilities added',
      'No waitlisted applications yet': 'No waitlisted applications yet',
      'Not provided': 'Not provided',
      'Not shortlisted': 'Not shortlisted',
      'Not sure': 'Not sure',
      'Oldest': 'Oldest',
      'Optional note': 'Optional note',
      'Organisation Details': 'Organisation Details',
      'Organisation Name': 'Organisation Name',
      'Organiser Verification': 'Organiser Verification',
      'OTP sent to your phone number': 'OTP sent to your phone number',
      'Our Mission': 'Our Mission',
      'Paid': 'Paid',
      'PAN Card': 'PAN Card',
      'Partially available': 'Partially available',
      'Passport': 'Passport',
      'Password': 'Password',
      'Password must be at least 6 characters': 'Password must be at least 6 characters',
      'Password updated successfully': 'Password updated successfully',
      'Passwords do not match': 'Passwords do not match',
      'Past Event Categories': 'Past Event Categories',
      'Payment Amount': 'Payment Amount',
      'Payment Clearance Date': 'Payment Clearance Date',
      'Payment clearance date cannot be before the event end date': 'Payment clearance date cannot be before the event end date',
      'Payment Rate': 'Payment Rate',
      'Pending / Waitlisted': 'Pending / Waitlisted',
      'Per Day': 'Per Day',
      'Per Hour': 'Per Hour',
      'Phone Number': 'Phone Number',
      'Phone number updated successfully': 'Phone number updated successfully',
      'Please provide cancellation reason': 'Please provide cancellation reason',
      'Preferences': 'Preferences',
      'Present': 'Present',
      'Promotional Notifications': 'Promotional Notifications',
      'Proof Selected': 'Proof Selected',
      'Publish': 'Publish',
      'Publish Event': 'Publish Event',
      'Rate Volunteer': 'Rate Volunteer',
      'Recent Participation': 'Recent Participation',
      'Removed from shortlist': 'Removed from shortlist',
      'Responsibilities': 'Responsibilities',
      'Review volunteer applications': 'Review volunteer applications',
      'Save Attendance': 'Save Attendance',
      'Save Draft': 'Save Draft',
      'Schedule': 'Schedule',
      'Select a cancellation reason': 'Select a cancellation reason',
      'Select application deadline': 'Select application deadline',
      'Select at least one category': 'Select at least one category',
      'Select event start and end dates': 'Select event start and end dates',
      'Select event start and end time': 'Select event start and end time',
      'Select payment clearance date': 'Select payment clearance date',
      'Select start and end dates first': 'Select start and end dates first',
      'Send': 'Send',
      'Send Announcement': 'Send Announcement',
      'Send OTP': 'Send OTP',
      'Sending...': 'Sending...',
      'Shortlist:': 'Shortlist:',
      'Shortlisted': 'Shortlisted',
      'Show contact number to volunteers': 'Show contact number to volunteers',
      'Start Date': 'Start Date',
      'Start Time': 'Start Time',
      'This action is irreversible. All data will be lost.': 'This action is irreversible. All data will be lost.',
      'This application can no longer be changed.': 'This application can no longer be changed.',
      'This application has been cancelled.': 'This application has been cancelled.',
      'This application is already approved.': 'This application is already approved.',
      'This application is already rejected.': 'This application is already rejected.',
      'This participation is already completed.': 'This participation is already completed.',
      'Token missing. Please login again.': 'Token missing. Please login again.',
      'Top badge: {badge}': 'Top badge: {badge}',
      'Track volunteer performance': 'Track volunteer performance',
      'Type announcement...': 'Type announcement...',
      'Unpaid': 'Unpaid',
      'Update Email': 'Update Email',
      'Update Event': 'Update Event',
      'Update failed': 'Update failed',
      'Update Password': 'Update Password',
      'Update Phone Number': 'Update Phone Number',
      'Upload Event Banner (Optional)': 'Upload Event Banner (Optional)',
      'Upload Event Proof / Certificate': 'Upload Event Proof / Certificate',
      'Verification email sent to new address': 'Verification email sent to new address',
      'Verify OTP': 'Verify OTP',
      'Version': 'Version',
      'View Application': 'View Application',
      'View Volunteers': 'View Volunteers',
    'Mark Attendance': 'Mark Attendance',
      'volunteer': 'volunteer',
      'volunteers': 'volunteers',
      'Volunteers Required': 'Volunteers Required',
      'VolunteerX v1.0.0': 'VolunteerX v1.0.0',
      'Waitlisted': 'Waitlisted',
      'Website / Social Link': 'Website / Social Link',
      'What is VolunteerX?': 'What is VolunteerX?',
      'What You Can Do': 'What You Can Do',
      'Write a message for volunteers in this event.': 'Write a message for volunteers in this event.',
      'Write cancellation reason': 'Write cancellation reason',
      'Your account will be temporarily disabled.': 'Your account will be temporarily disabled.',
      'About this Event': 'About this Event',
      'Appeal approved': 'Appeal approved',
      'Appeal available': 'Appeal available',
      'Appeal pending': 'Appeal pending',
      'Appeal reason': 'Appeal reason',
      'Appeal rejected': 'Appeal rejected',
      'Application Approved': 'Application Approved',
      'Application Cancelled': 'Application Cancelled',
      'Application Pending': 'Application Pending',
      'Application Rejected': 'Application Rejected',
      'Application Status Updated': 'Application Status Updated',
      'Application Waitlisted': 'Application Waitlisted',
      'Applications closed': 'Applications closed',
      'Applied Events': 'Applied Events',
      'Apply for this Event': 'Apply for this Event',
      'Attendance Absent': 'Attendance Absent',
      'Attendance absent': 'Attendance absent',
      'Attendance present': 'Attendance present',
      'Availability for this event': 'Availability for this event',
      'Cancel Participation': 'Cancel Participation',
      'Cancel Participation (Locked)': 'Cancel Participation (Locked)',
      'Clear': 'Clear',
      'Close search': 'Close search',
      'Confirm & Apply': 'Confirm & Apply',
      'Confirm Cancel': 'Confirm Cancel',
    'Couldn\'t verify your account status. Please try again.': 'Couldn\'t verify your account status. Please try again.',
      'Date': 'Date',
      'Date not available': 'Date not available',
      'Document uploaded': 'Document uploaded',
      'Event cancelled': 'Event cancelled',
      'Event completed': 'Event completed',
      'Event not found': 'Event not found',
      'Event removed': 'Event removed',
      'Failed to load event details': 'Failed to load event details',
      'Failed to load saved events.': 'Failed to load saved events.',
      'Filter Events': 'Filter Events',
      'Filters': 'Filters',
      'fixed amount': 'fixed amount',
      'I agree to the Terms & Conditions': 'I agree to the Terms & Conditions',
      'Join on VolunteerX': 'Join on VolunteerX',
      'Keep': 'Keep',
      'No applications found': 'No applications found',
      'No document uploaded': 'No document uploaded',
      'No responsibilities provided by organiser.': 'No responsibilities provided by organiser.',
      'No saved events yet': 'No saved events yet',
      'No volunteer history yet': 'No volunteer history yet',
      'Open': 'Open',
      'Open Events': 'Open Events',
      'Organiser profile not available': 'Organiser profile not available',
      'Participation cancelled.': 'Participation cancelled.',
      'Participation cancelled. A strike was applied.': 'Participation cancelled. A strike was applied.',
      'Past': 'Past',
      'per day': 'per day',
      'per hour': 'per hour',
      'Prior Experience (optional)': 'Prior Experience (optional)',
      'Rate organiser': 'Rate organiser',
      'Rate Organiser': 'Rate Organiser',
      'Reason (optional but recommended)': 'Reason (optional but recommended)',
      'Reason *': 'Reason *',
      'Reason is mandatory within 48 hours': 'Reason is mandatory within 48 hours',
      'Remove from saved': 'Remove from saved',
      'Removed from saved': 'Removed from saved',
      'Save event': 'Save event',
      'Saved event': 'Saved event',
      'Search': 'Search',
      'Strike appeal submitted': 'Strike appeal submitted',
      'Strike applied': 'Strike applied',
      'Submit Appeal': 'Submit Appeal',
      'Submit appeal': 'Submit appeal',
      'Submit Strike Appeal': 'Submit Strike Appeal',
      'Supporting document': 'Supporting document',
      'Supporting document *': 'Supporting document *',
      'This application was cancelled.': 'This application was cancelled.',
      'This application was not approved.': 'This application was not approved.',
      'This event ended before your application was reviewed.':
          'This event ended before your application was reviewed.',
      'This event ended before this application could be reviewed.':
          'This event ended before this application could be reviewed.',
      'Unable to apply': 'Unable to apply',
      'Upload': 'Upload',
      'Verification Required': 'Verification Required',
      'Verification required to apply': 'Verification required to apply',
      'View organiser profile': 'View organiser profile',
      'Volunteer Terms & Conditions': 'Volunteer Terms & Conditions',
      'Warning issued': 'Warning issued',
      'You are confirmed for this event.': 'You are confirmed for this event.',
      'You were marked absent for this event.': 'You were marked absent for this event.',
      'Your application is under review.': 'Your application is under review.',
      'Your attendance was marked present for this event.': 'Your attendance was marked present for this event.',
      'Your participation for this event is completed.': 'Your participation for this event is completed.',
      'Your Responsibilities': 'Your Responsibilities',
    },
    'hi': {
      'App Language': 'à¤à¤ª à¤­à¤¾à¤·à¤¾',
      'Choose Language': 'à¤­à¤¾à¤·à¤¾ à¤šà¥à¤¨à¥‡à¤‚',
      'English': 'à¤…à¤‚à¤—à¥à¤°à¥‡à¤œà¤¼à¥€',
      'Hindi': 'à¤¹à¤¿à¤¨à¥à¤¦à¥€',
      'Language': 'à¤­à¤¾à¤·à¤¾',
      'Volunteer': 'à¤¸à¥à¤µà¤¯à¤‚à¤¸à¥‡à¤µà¤•',
      'Hi, {name}!': 'à¤¨à¤®à¤¸à¥à¤¤à¥‡, {name}!',
      'Find your next volunteer event': 'à¤…à¤ªà¤¨à¤¾ à¤…à¤—à¤²à¤¾ à¤¸à¥à¤µà¤¯à¤‚à¤¸à¥‡à¤µà¤¾ à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤® à¤–à¥‹à¤œà¥‡à¤‚',
      'My Ongoing Events': 'à¤®à¥‡à¤°à¥‡ à¤šà¤² à¤°à¤¹à¥‡ à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤®',
      'My Upcoming Events': 'à¤®à¥‡à¤°à¥‡ à¤†à¤—à¤¾à¤®à¥€ à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤®',
      'Upcoming': 'à¤†à¤—à¤¾à¤®à¥€',
      'Ongoing': 'à¤šà¤² à¤°à¤¹à¥‡',
      'No ongoing events yet': 'à¤…à¤­à¥€ à¤•à¥‹à¤ˆ à¤šà¤² à¤°à¤¹à¤¾ à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤® à¤¨à¤¹à¥€à¤‚ à¤¹à¥ˆ',
      'No upcoming events yet': 'à¤…à¤­à¥€ à¤•à¥‹à¤ˆ à¤†à¤—à¤¾à¤®à¥€ à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤® à¤¨à¤¹à¥€à¤‚ à¤¹à¥ˆ',
      'View All': 'à¤¸à¤­à¥€ à¤¦à¥‡à¤–à¥‡à¤‚',
      'Recommended for You': 'à¤†à¤ªà¤•à¥‡ à¤²à¤¿à¤ à¤¸à¥à¤à¤¾à¤ à¤—à¤',
      'No recommendations available': 'à¤•à¥‹à¤ˆ à¤¸à¥à¤à¤¾à¤µ à¤‰à¤ªà¤²à¤¬à¥à¤§ à¤¨à¤¹à¥€à¤‚',
      'Event details not available': 'à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤® à¤•à¤¾ à¤µà¤¿à¤µà¤°à¤£ à¤‰à¤ªà¤²à¤¬à¥à¤§ à¤¨à¤¹à¥€à¤‚',
      'Failed to open event details': 'à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤® à¤•à¤¾ à¤µà¤¿à¤µà¤°à¤£ à¤–à¥‹à¤²à¤¨à¥‡ à¤®à¥‡à¤‚ à¤µà¤¿à¤«à¤²',
      'Pending Rating Reminder': 'à¤°à¥‡à¤Ÿà¤¿à¤‚à¤— à¤²à¤‚à¤¬à¤¿à¤¤ à¤¹à¥ˆ',
      'Share your feedback for {event}.': '{event} à¤•à¥‡ à¤²à¤¿à¤ à¤…à¤ªà¤¨à¤¾ à¤«à¥€à¤¡à¤¬à¥ˆà¤• à¤¦à¥‡à¤‚à¥¤',
      '{count} completed events are waiting for your rating.':
          '{count} à¤ªà¥‚à¤°à¥à¤£ à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤® à¤†à¤ªà¤•à¥€ à¤°à¥‡à¤Ÿà¤¿à¤‚à¤— à¤•à¥€ à¤ªà¥à¤°à¤¤à¥€à¤•à¥à¤·à¤¾ à¤•à¤° à¤°à¤¹à¥‡ à¤¹à¥ˆà¤‚à¥¤',
      'Rate now': 'à¤…à¤­à¥€ à¤°à¥‡à¤Ÿ à¤•à¤°à¥‡à¤‚',
      'View Details': 'à¤µà¤¿à¤µà¤°à¤£ à¤¦à¥‡à¤–à¥‡à¤‚',
      '{filled}/{required} approved': '{filled}/{required} à¤¸à¥à¤µà¥€à¤•à¥ƒà¤¤',
      'Pending': 'à¤²à¤‚à¤¬à¤¿à¤¤',
      'Approved': 'à¤¸à¥à¤µà¥€à¤•à¥ƒà¤¤',
      'Rejected': 'à¤…à¤¸à¥à¤µà¥€à¤•à¥ƒà¤¤',
      'Review Closed': 'à¤¸à¤®à¥€à¤•à¥à¤·à¤¾ à¤¬à¤‚à¤¦',
      'Cancelled': 'à¤°à¤¦à¥à¤¦',
      'Apply': 'à¤†à¤µà¥‡à¤¦à¤¨ à¤•à¤°à¥‡à¤‚',
      'Home': 'à¤¹à¥‹à¤®',
      'Events': 'à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤®',
      'Leaderboard': 'à¤²à¥€à¤¡à¤°à¤¬à¥‹à¤°à¥à¤¡',
      'Profile': 'à¤ªà¥à¤°à¥‹à¤«à¤¼à¤¾à¤‡à¤²',
      'event': 'à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤®',
      'Failed to load events. Pull to refresh or tap Retry.':
          'à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤® à¤²à¥‹à¤¡ à¤¨à¤¹à¥€à¤‚ à¤¹à¥‹ à¤ªà¤¾à¤à¥¤ à¤°à¥€à¤«à¤¼à¥à¤°à¥‡à¤¶ à¤•à¤°à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ à¤¨à¥€à¤šà¥‡ à¤–à¥€à¤‚à¤šà¥‡à¤‚ à¤¯à¤¾ à¤ªà¥à¤¨à¤ƒ à¤ªà¥à¤°à¤¯à¤¾à¤¸ à¤•à¤°à¥‡à¤‚à¥¤',
      'Your verification is under review. You can create events after approval.':
          'à¤†à¤ªà¤•à¤¾ à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¨ à¤¸à¤®à¥€à¤•à¥à¤·à¤¾ à¤®à¥‡à¤‚ à¤¹à¥ˆà¥¤ à¤¸à¥à¤µà¥€à¤•à¥ƒà¤¤à¤¿ à¤•à¥‡ à¤¬à¤¾à¤¦ à¤†à¤ª à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤® à¤¬à¤¨à¤¾ à¤¸à¤•à¤¤à¥‡ à¤¹à¥ˆà¤‚à¥¤',
      'Your verification was rejected. Please submit verification again to create events.':
          'à¤†à¤ªà¤•à¤¾ à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¨ à¤…à¤¸à¥à¤µà¥€à¤•à¥ƒà¤¤ à¤¹à¥‹ à¤—à¤¯à¤¾à¥¤ à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤® à¤¬à¤¨à¤¾à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ à¤«à¤¿à¤° à¤¸à¥‡ à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¨ à¤­à¥‡à¤œà¥‡à¤‚à¥¤',
      'You need to be verified before creating events.':
          'à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤® à¤¬à¤¨à¤¾à¤¨à¥‡ à¤¸à¥‡ à¤ªà¤¹à¤²à¥‡ à¤†à¤ªà¤•à¤¾ à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¨ à¤†à¤µà¤¶à¥à¤¯à¤• à¤¹à¥ˆà¥¤',
      'Unable to verify your account right now. Please try again.':
          'à¤…à¤­à¥€ à¤†à¤ªà¤•à¤¾ à¤–à¤¾à¤¤à¤¾ à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¿à¤¤ à¤¨à¤¹à¥€à¤‚ à¤•à¤¿à¤¯à¤¾ à¤œà¤¾ à¤¸à¤•à¤¾à¥¤ à¤•à¥ƒà¤ªà¤¯à¤¾ à¤«à¤¿à¤° à¤¸à¥‡ à¤ªà¥à¤°à¤¯à¤¾à¤¸ à¤•à¤°à¥‡à¤‚à¥¤',
      'Create Event': 'à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤® à¤¬à¤¨à¤¾à¤à¤‚',
      'All': 'à¤¸à¤­à¥€',
      'Completed': 'à¤ªà¥‚à¤°à¥à¤£',
      'Draft': 'à¤®à¤¸à¥Œà¤¦à¤¾',
      'Retry': 'à¤ªà¥à¤¨à¤ƒ à¤ªà¥à¤°à¤¯à¤¾à¤¸ à¤•à¤°à¥‡à¤‚',
      'All Events': 'à¤¸à¤­à¥€ à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤®',
      'Ongoing Events': 'à¤šà¤² à¤°à¤¹à¥‡ à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤®',
      'Upcoming Events': 'à¤†à¤—à¤¾à¤®à¥€ à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤®',
      'Completed Events': 'à¤ªà¥‚à¤°à¥à¤£ à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤®',
      'Draft Events': 'à¤®à¤¸à¥Œà¤¦à¤¾ à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤®',
      'Cancelled Events': 'à¤°à¤¦à¥à¤¦ à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤®',
      'No {title}': 'à¤•à¥‹à¤ˆ {title} à¤¨à¤¹à¥€à¤‚',
      'Organiser: {name}': 'à¤†à¤¯à¥‹à¤œà¤•: {name}',
      'Untitled': 'à¤¶à¥€à¤°à¥à¤·à¤• à¤¨à¤¹à¥€à¤‚',
      'Location: {location}': 'à¤¸à¥à¤¥à¤¾à¤¨: {location}',
      'N/A': 'à¤‰à¤ªà¤²à¤¬à¥à¤§ à¤¨à¤¹à¥€à¤‚',
      'Date: {date}': 'à¤¤à¤¾à¤°à¥€à¤–: {date}',
      'No ratings yet': 'à¤…à¤­à¥€ à¤¤à¤• à¤•à¥‹à¤ˆ à¤°à¥‡à¤Ÿà¤¿à¤‚à¤— à¤¨à¤¹à¥€à¤‚',
      'Review': 'à¤¸à¤®à¥€à¤•à¥à¤·à¤¾',
      'Removed by admin': 'à¤à¤¡à¤®à¤¿à¤¨ à¤¦à¥à¤µà¤¾à¤°à¤¾ à¤¹à¤Ÿà¤¾à¤¯à¤¾ à¤—à¤¯à¤¾',
      'Not published': 'à¤ªà¥à¤°à¤•à¤¾à¤¶à¤¿à¤¤ à¤¨à¤¹à¥€à¤‚',
      'Cancelled by organiser': 'à¤†à¤¯à¥‹à¤œà¤• à¤¦à¥à¤µà¤¾à¤°à¤¾ à¤°à¤¦à¥à¤¦',
      'Starts today': 'à¤†à¤œ à¤¶à¥à¤°à¥‚ à¤¹à¥‹à¤¤à¤¾ à¤¹à¥ˆ',
      'Starts in {days}d': '{days} à¤¦à¤¿à¤¨ à¤®à¥‡à¤‚ à¤¶à¥à¤°à¥‚',
      'Deadline passed': 'à¤¸à¤®à¤¯-à¤¸à¥€à¤®à¤¾ à¤¸à¤®à¤¾à¤ªà¥à¤¤',
      'Deadline soon': 'à¤¸à¤®à¤¯-à¤¸à¥€à¤®à¤¾ à¤œà¤²à¥à¤¦',
      'Approved: {accepted} / {required}': 'à¤¸à¥à¤µà¥€à¤•à¥ƒà¤¤: {accepted} / {required}',
      'Applicants: {raw} / {required}': 'à¤†à¤µà¥‡à¤¦à¤•: {raw} / {required}',
      'Draft not visible to volunteers': 'à¤®à¤¸à¥Œà¤¦à¤¾ à¤¸à¥à¤µà¤¯à¤‚à¤¸à¥‡à¤µà¤•à¥‹à¤‚ à¤•à¥‹ à¤¦à¤¿à¤–à¤¾à¤ˆ à¤¨à¤¹à¥€à¤‚ à¤¦à¥‡à¤¤à¤¾',
      'Application deadline passed': 'à¤†à¤µà¥‡à¤¦à¤¨ à¤•à¥€ à¤¸à¤®à¤¯-à¤¸à¥€à¤®à¤¾ à¤¸à¤®à¤¾à¤ªà¥à¤¤',
      'No applications yet': 'à¤…à¤­à¥€ à¤¤à¤• à¤•à¥‹à¤ˆ à¤†à¤µà¥‡à¤¦à¤¨ à¤¨à¤¹à¥€à¤‚',
      'Understaffed by {count}': '{count} à¤¸à¥à¤µà¤¯à¤‚à¤¸à¥‡à¤µà¤• à¤•à¤® à¤¹à¥ˆà¤‚',
      'to': 'à¤¸à¥‡',
      'Help & Support': 'à¤¸à¤¹à¤¾à¤¯à¤¤à¤¾ à¤”à¤° à¤¸à¤®à¤°à¥à¤¥à¤¨',
      'FAQs': 'à¤¸à¤¾à¤®à¤¾à¤¨à¥à¤¯ à¤ªà¥à¤°à¤¶à¥à¤¨',
      'Common questions answered': 'à¤¸à¤¾à¤®à¤¾à¤¨à¥à¤¯ à¤ªà¥à¤°à¤¶à¥à¤¨à¥‹à¤‚ à¤•à¥‡ à¤‰à¤¤à¥à¤¤à¤°',
      'App Support': 'à¤à¤ª à¤¸à¤¹à¤¾à¤¯à¤¤à¤¾',
      'Issues with the app or login': 'à¤à¤ª à¤¯à¤¾ à¤²à¥‰à¤—à¤¿à¤¨ à¤¸à¥‡ à¤œà¥à¤¡à¤¼à¥€ à¤¸à¤®à¤¸à¥à¤¯à¤¾à¤à¤‚',
      'App not loading events?': 'à¤à¤ª à¤®à¥‡à¤‚ à¤‡à¤µà¥‡à¤‚à¤Ÿà¥à¤¸ à¤²à¥‹à¤¡ à¤¨à¤¹à¥€à¤‚ à¤¹à¥‹ à¤°à¤¹à¥‡?',
      'Check your internet connection and try again.':
          'à¤…à¤ªà¤¨à¤¾ à¤‡à¤‚à¤Ÿà¤°à¤¨à¥‡à¤Ÿ à¤•à¤¨à¥‡à¤•à¥à¤¶à¤¨ à¤œà¤¾à¤‚à¤šà¥‡à¤‚ à¤”à¤° à¤«à¤¿à¤° à¤¸à¥‡ à¤ªà¥à¤°à¤¯à¤¾à¤¸ à¤•à¤°à¥‡à¤‚à¥¤',
      'Login issues?': 'à¤²à¥‰à¤—à¤¿à¤¨ à¤¸à¤®à¤¸à¥à¤¯à¤¾?',
      'Make sure your credentials are correct or use Forgot Password.':
          "à¤¸à¥à¤¨à¤¿à¤¶à¥à¤šà¤¿à¤¤ à¤•à¤°à¥‡à¤‚ à¤•à¤¿ à¤†à¤ªà¤•à¥‡ à¤•à¥à¤°à¥‡à¤¡à¥‡à¤‚à¤¶à¤¿à¤¯à¤² à¤¸à¤¹à¥€ à¤¹à¥ˆà¤‚ à¤¯à¤¾ 'Forgot Password' à¤•à¤¾ à¤‰à¤ªà¤¯à¥‹à¤— à¤•à¤°à¥‡à¤‚à¥¤",
      'App crashes or bugs?': 'à¤à¤ª à¤•à¥à¤°à¥ˆà¤¶ à¤¯à¤¾ à¤¬à¤—?',
      'Restart the app or update to the latest version.':
          'à¤à¤ª à¤•à¥‹ à¤°à¥€à¤¸à¥à¤Ÿà¤¾à¤°à¥à¤Ÿ à¤•à¤°à¥‡à¤‚ à¤¯à¤¾ à¤¨à¤µà¥€à¤¨à¤¤à¤® à¤¸à¤‚à¤¸à¥à¤•à¤°à¤£ à¤®à¥‡à¤‚ à¤…à¤ªà¤¡à¥‡à¤Ÿ à¤•à¤°à¥‡à¤‚à¥¤',
      'Still facing issues?': 'à¤…à¤¬ à¤­à¥€ à¤¸à¤®à¤¸à¥à¤¯à¤¾ à¤¹à¥ˆ?',
      'Contact our support team via email.':
          'à¤ˆà¤®à¥‡à¤² à¤•à¥‡ à¤®à¤¾à¤§à¥à¤¯à¤® à¤¸à¥‡ à¤¹à¤®à¤¾à¤°à¥€ à¤¸à¤¹à¤¾à¤¯à¤¤à¤¾ à¤Ÿà¥€à¤® à¤¸à¥‡ à¤¸à¤‚à¤ªà¤°à¥à¤• à¤•à¤°à¥‡à¤‚à¥¤',
      'Safety & Guidelines': 'à¤¸à¥à¤°à¤•à¥à¤·à¤¾ à¤”à¤° à¤¦à¤¿à¤¶à¤¾à¤¨à¤¿à¤°à¥à¤¦à¥‡à¤¶',
      'Your safety matters': 'à¤†à¤ªà¤•à¥€ à¤¸à¥à¤°à¤•à¥à¤·à¤¾ à¤®à¤¹à¤¤à¥à¤µà¤ªà¥‚à¤°à¥à¤£ à¤¹à¥ˆ',
      'Always verify event details before attending.':
          'à¤¶à¤¾à¤®à¤¿à¤² à¤¹à¥‹à¤¨à¥‡ à¤¸à¥‡ à¤ªà¤¹à¤²à¥‡ à¤‡à¤µà¥‡à¤‚à¤Ÿ à¤µà¤¿à¤µà¤°à¤£ à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¿à¤¤ à¤•à¤°à¥‡à¤‚à¥¤',
      'Avoid sharing personal or financial information.':
          'à¤µà¥à¤¯à¤•à¥à¤¤à¤¿à¤—à¤¤ à¤¯à¤¾ à¤µà¤¿à¤¤à¥à¤¤à¥€à¤¯ à¤œà¤¾à¤¨à¤•à¤¾à¤°à¥€ à¤¸à¤¾à¤à¤¾ à¤•à¤°à¤¨à¥‡ à¤¸à¥‡ à¤¬à¤šà¥‡à¤‚à¥¤',
      'Report suspicious organisers or events immediately.':
          'à¤¸à¤‚à¤¦à¤¿à¤—à¥à¤§ à¤†à¤¯à¥‹à¤œà¤•à¥‹à¤‚ à¤¯à¤¾ à¤‡à¤µà¥‡à¤‚à¤Ÿà¥à¤¸ à¤•à¥€ à¤¤à¥à¤°à¤‚à¤¤ à¤°à¤¿à¤ªà¥‹à¤°à¥à¤Ÿ à¤•à¤°à¥‡à¤‚à¥¤',
      'Follow community guidelines and event instructions.':
          'à¤¸à¤®à¥à¤¦à¤¾à¤¯ à¤¦à¤¿à¤¶à¤¾à¤¨à¤¿à¤°à¥à¤¦à¥‡à¤¶ à¤”à¤° à¤‡à¤µà¥‡à¤‚à¤Ÿ à¤¨à¤¿à¤°à¥à¤¦à¥‡à¤¶à¥‹à¤‚ à¤•à¤¾ à¤ªà¤¾à¤²à¤¨ à¤•à¤°à¥‡à¤‚à¥¤',
      'Contact Us': 'à¤¸à¤‚à¤ªà¤°à¥à¤• à¤•à¤°à¥‡à¤‚',
      'Get in touch with our team': 'à¤¹à¤®à¤¾à¤°à¥€ à¤Ÿà¥€à¤® à¤¸à¥‡ à¤¸à¤‚à¤ªà¤°à¥à¤• à¤•à¤°à¥‡à¤‚',
      'Contact VolunteerX': 'VolunteerX à¤¸à¥‡ à¤¸à¤‚à¤ªà¤°à¥à¤• à¤•à¤°à¥‡à¤‚',
      'Email Support': 'à¤ˆà¤®à¥‡à¤² à¤¸à¤¹à¤¾à¤¯à¤¤à¤¾',
      'Our team usually responds within 24-48 hours.':
          'à¤¹à¤®à¤¾à¤°à¥€ à¤Ÿà¥€à¤® à¤†à¤®à¤¤à¥Œà¤° à¤ªà¤° 24-48 à¤˜à¤‚à¤Ÿà¥‹à¤‚ à¤®à¥‡à¤‚ à¤œà¤µà¤¾à¤¬ à¤¦à¥‡à¤¤à¥€ à¤¹à¥ˆà¥¤',
      'Please include screenshots or details for faster support.':
          'à¤¤à¥‡à¤œà¤¼ à¤¸à¤¹à¤¾à¤¯à¤¤à¤¾ à¤•à¥‡ à¤²à¤¿à¤ à¤•à¥ƒà¤ªà¤¯à¤¾ à¤¸à¥à¤•à¥à¤°à¥€à¤¨à¤¶à¥‰à¤Ÿ à¤¯à¤¾ à¤µà¤¿à¤µà¤°à¤£ à¤¶à¤¾à¤®à¤¿à¤² à¤•à¤°à¥‡à¤‚à¥¤',
      'Frequently Asked Questions': 'à¤…à¤•à¥à¤¸à¤° à¤ªà¥‚à¤›à¥‡ à¤œà¤¾à¤¨à¥‡ à¤µà¤¾à¤²à¥‡ à¤ªà¥à¤°à¤¶à¥à¤¨',
      'What is the strike/suspension policy?':
          'à¤¸à¥à¤Ÿà¥à¤°à¤¾à¤‡à¤•/à¤¨à¤¿à¤²à¤‚à¤¬à¤¨ à¤¨à¥€à¤¤à¤¿ à¤•à¥à¤¯à¤¾ à¤¹à¥ˆ?',
      'Repeated violations may lead to strikes. 2 strikes: 3-day suspension, 3 strikes: 7-day suspension, 4 strikes: account ban.':
          'à¤¬à¤¾à¤°-à¤¬à¤¾à¤° à¤‰à¤²à¥à¤²à¤‚à¤˜à¤¨ à¤•à¤°à¤¨à¥‡ à¤ªà¤° à¤¸à¥à¤Ÿà¥à¤°à¤¾à¤‡à¤• à¤²à¤— à¤¸à¤•à¤¤à¥€ à¤¹à¥ˆà¥¤ 2 à¤¸à¥à¤Ÿà¥à¤°à¤¾à¤‡à¤•: 3 à¤¦à¤¿à¤¨à¥‹à¤‚ à¤•à¤¾ à¤¨à¤¿à¤²à¤‚à¤¬à¤¨, 3 à¤¸à¥à¤Ÿà¥à¤°à¤¾à¤‡à¤•: 7 à¤¦à¤¿à¤¨à¥‹à¤‚ à¤•à¤¾ à¤¨à¤¿à¤²à¤‚à¤¬à¤¨, 4 à¤¸à¥à¤Ÿà¥à¤°à¤¾à¤‡à¤•: à¤–à¤¾à¤¤à¤¾ à¤ªà¥à¤°à¤¤à¤¿à¤¬à¤‚à¤§à¥¤',
      'How do I apply for an event?': 'à¤®à¥ˆà¤‚ à¤•à¤¿à¤¸à¥€ à¤‡à¤µà¥‡à¤‚à¤Ÿ à¤•à¥‡ à¤²à¤¿à¤ à¤†à¤µà¥‡à¤¦à¤¨ à¤•à¥ˆà¤¸à¥‡ à¤•à¤°à¥‚à¤‚?',
      'Open an event card and tap Apply. Fill required details and submit your application.':
          'à¤•à¤¿à¤¸à¥€ à¤‡à¤µà¥‡à¤‚à¤Ÿ à¤•à¤¾à¤°à¥à¤¡ à¤•à¥‹ à¤–à¥‹à¤²à¥‡à¤‚ à¤”à¤° Apply à¤ªà¤° à¤Ÿà¥ˆà¤ª à¤•à¤°à¥‡à¤‚à¥¤ à¤†à¤µà¤¶à¥à¤¯à¤• à¤µà¤¿à¤µà¤°à¤£ à¤­à¤°à¥‡à¤‚ à¤”à¤° à¤†à¤µà¥‡à¤¦à¤¨ à¤¸à¤¬à¤®à¤¿à¤Ÿ à¤•à¤°à¥‡à¤‚à¥¤',
      'Can I cancel my application?': 'à¤•à¥à¤¯à¤¾ à¤®à¥ˆà¤‚ à¤…à¤ªà¤¨à¤¾ à¤†à¤µà¥‡à¤¦à¤¨ à¤°à¤¦à¥à¤¦ à¤•à¤° à¤¸à¤•à¤¤à¤¾ à¤¹à¥‚à¤‚?',
      'Yes. If cancellation is available for that event, you can cancel from your application details.':
          'à¤¹à¤¾à¤‚à¥¤ à¤¯à¤¦à¤¿ à¤‰à¤¸ à¤‡à¤µà¥‡à¤‚à¤Ÿ à¤•à¥‡ à¤²à¤¿à¤ à¤°à¤¦à¥à¤¦ à¤•à¤°à¤¨à¤¾ à¤‰à¤ªà¤²à¤¬à¥à¤§ à¤¹à¥ˆ, à¤¤à¥‹ à¤†à¤ª à¤†à¤µà¥‡à¤¦à¤¨ à¤µà¤¿à¤µà¤°à¤£ à¤¸à¥‡ à¤°à¤¦à¥à¤¦ à¤•à¤° à¤¸à¤•à¤¤à¥‡ à¤¹à¥ˆà¤‚à¥¤',
      'How are badges earned?': 'à¤¬à¥ˆà¤œ à¤•à¥ˆà¤¸à¥‡ à¤®à¤¿à¤²à¤¤à¥‡ à¤¹à¥ˆà¤‚?',
      'Badges are awarded based on completed events and consistent participation.':
          'à¤¬à¥ˆà¤œ à¤ªà¥‚à¤°à¥à¤£ à¤•à¤¿à¤ à¤—à¤ à¤‡à¤µà¥‡à¤‚à¤Ÿà¥à¤¸ à¤”à¤° à¤¨à¤¿à¤¯à¤®à¤¿à¤¤ à¤¸à¤¹à¤­à¤¾à¤—à¤¿à¤¤à¤¾ à¤•à¥‡ à¤†à¤§à¤¾à¤° à¤ªà¤° à¤¦à¤¿à¤ à¤œà¤¾à¤¤à¥‡ à¤¹à¥ˆà¤‚à¥¤',
      'How do paid event payments work?': 'à¤ªà¥‡à¤¡ à¤‡à¤µà¥‡à¤‚à¤Ÿ à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤•à¥ˆà¤¸à¥‡ à¤•à¤¾à¤® à¤•à¤°à¤¤à¥‡ à¤¹à¥ˆà¤‚?',
      'Payment status depends on organiser confirmation and event completion.':
          'à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤¸à¥à¤¥à¤¿à¤¤à¤¿ à¤†à¤¯à¥‹à¤œà¤• à¤•à¥€ à¤ªà¥à¤·à¥à¤Ÿà¤¿ à¤”à¤° à¤‡à¤µà¥‡à¤‚à¤Ÿ à¤ªà¥‚à¤°à¤¾ à¤¹à¥‹à¤¨à¥‡ à¤ªà¤° à¤¨à¤¿à¤°à¥à¤­à¤° à¤•à¤°à¤¤à¥€ à¤¹à¥ˆà¥¤',
      'Why are events not loading?': 'à¤‡à¤µà¥‡à¤‚à¤Ÿà¥à¤¸ à¤²à¥‹à¤¡ à¤•à¥à¤¯à¥‹à¤‚ à¤¨à¤¹à¥€à¤‚ à¤¹à¥‹ à¤°à¤¹à¥‡?',
      'Check your internet connection, then refresh the page. If it persists, contact support.':
          'à¤…à¤ªà¤¨à¤¾ à¤‡à¤‚à¤Ÿà¤°à¤¨à¥‡à¤Ÿ à¤•à¤¨à¥‡à¤•à¥à¤¶à¤¨ à¤œà¤¾à¤‚à¤šà¥‡à¤‚, à¤«à¤¿à¤° à¤ªà¥‡à¤œ à¤°à¤¿à¤«à¥à¤°à¥‡à¤¶ à¤•à¤°à¥‡à¤‚à¥¤ à¤¯à¤¦à¤¿ à¤¸à¤®à¤¸à¥à¤¯à¤¾ à¤¬à¤¨à¥€ à¤°à¤¹à¥‡, à¤¤à¥‹ à¤¸à¤¹à¤¾à¤¯à¤¤à¤¾ à¤¸à¥‡ à¤¸à¤‚à¤ªà¤°à¥à¤• à¤•à¤°à¥‡à¤‚à¥¤',
      'What if I face login issues?': 'à¤¯à¤¦à¤¿ à¤®à¥à¤à¥‡ à¤²à¥‰à¤—à¤¿à¤¨ à¤¸à¤®à¤¸à¥à¤¯à¤¾ à¤¹à¥‹ à¤¤à¥‹ à¤•à¥à¤¯à¤¾ à¤•à¤°à¥‡à¤‚?',
      'Verify your credentials and try Forgot Password if needed.':
          'à¤…à¤ªà¤¨à¥‡ à¤•à¥à¤°à¥‡à¤¡à¥‡à¤‚à¤¶à¤¿à¤¯à¤² à¤œà¤¾à¤‚à¤šà¥‡à¤‚ à¤”à¤° à¤œà¤°à¥‚à¤°à¤¤ à¤¹à¥‹ à¤¤à¥‹ Forgot Password à¤†à¤œà¤¼à¤®à¤¾à¤à¤‚à¥¤',
      'How can I improve my profile completion?':
          'à¤®à¥ˆà¤‚ à¤…à¤ªà¤¨à¤¾ à¤ªà¥à¤°à¥‹à¤«à¤¾à¤‡à¤² à¤ªà¥‚à¤°à¤¾ à¤•à¥ˆà¤¸à¥‡ à¤¸à¥à¤§à¤¾à¤°à¥‚à¤‚?',
      'Update your name, email, city, profile photo, and verification status in profile settings.':
          'à¤ªà¥à¤°à¥‹à¤«à¤¾à¤‡à¤² à¤¸à¥‡à¤Ÿà¤¿à¤‚à¤—à¥à¤¸ à¤®à¥‡à¤‚ à¤…à¤ªà¤¨à¤¾ à¤¨à¤¾à¤®, à¤ˆà¤®à¥‡à¤², à¤¶à¤¹à¤°, à¤ªà¥à¤°à¥‹à¤«à¤¾à¤‡à¤² à¤«à¥‹à¤Ÿà¥‹ à¤”à¤° à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¨ à¤¸à¥à¤¥à¤¿à¤¤à¤¿ à¤…à¤ªà¤¡à¥‡à¤Ÿ à¤•à¤°à¥‡à¤‚à¥¤',
      'How do I contact support?': 'à¤®à¥ˆà¤‚ à¤¸à¤¹à¤¾à¤¯à¤¤à¤¾ à¤¸à¥‡ à¤•à¥ˆà¤¸à¥‡ à¤¸à¤‚à¤ªà¤°à¥à¤• à¤•à¤°à¥‚à¤‚?',
      'Email volunteerxteam@gmail.com with screenshots and issue details for faster support.':
          'à¤¤à¥‡à¤œà¤¼ à¤¸à¤¹à¤¾à¤¯à¤¤à¤¾ à¤•à¥‡ à¤²à¤¿à¤ à¤¸à¥à¤•à¥à¤°à¥€à¤¨à¤¶à¥‰à¤Ÿ à¤”à¤° à¤¸à¤®à¤¸à¥à¤¯à¤¾ à¤µà¤¿à¤µà¤°à¤£ à¤•à¥‡ à¤¸à¤¾à¤¥ volunteerxteam@gmail.com à¤ªà¤° à¤ˆà¤®à¥‡à¤² à¤•à¤°à¥‡à¤‚à¥¤',
      'Token not found. Please login again.':
          'à¤Ÿà¥‹à¤•à¤¨ à¤¨à¤¹à¥€à¤‚ à¤®à¤¿à¤²à¤¾à¥¤ à¤•à¥ƒà¤ªà¤¯à¤¾ à¤«à¤¿à¤° à¤¸à¥‡ à¤²à¥‰à¤—à¤¿à¤¨ à¤•à¤°à¥‡à¤‚à¥¤',
      'Error {statusCode}: {message}': 'à¤¤à¥à¤°à¥à¤Ÿà¤¿ {statusCode}: {message}',
      'Error: {error}': 'à¤¤à¥à¤°à¥à¤Ÿà¤¿: {error}',
      'Name': 'à¤¨à¤¾à¤®',
      'Email': 'à¤ˆà¤®à¥‡à¤²',
      'City': 'à¤¶à¤¹à¤°',
      'Profile photo': 'à¤ªà¥à¤°à¥‹à¤«à¤¾à¤‡à¤² à¤«à¥‹à¤Ÿà¥‹',
      'Verification status': 'à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¨ à¤¸à¥à¤¥à¤¿à¤¤à¤¿',
      'Logout': 'à¤²à¥‰à¤—à¤†à¤‰à¤Ÿ',
      'Are you sure you want to logout?':
          'à¤•à¥à¤¯à¤¾ à¤†à¤ª à¤µà¤¾à¤•à¤ˆ à¤²à¥‰à¤—à¤†à¤‰à¤Ÿ à¤•à¤°à¤¨à¤¾ à¤šà¤¾à¤¹à¤¤à¥‡ à¤¹à¥ˆà¤‚?',
      'Cancel': 'à¤°à¤¦à¥à¤¦ à¤•à¤°à¥‡à¤‚',
      'Delete Account': 'à¤–à¤¾à¤¤à¤¾ à¤¹à¤Ÿà¤¾à¤à¤‚',
      'Are you sure you want to delete your account? This action is irreversible.':
          'à¤•à¥à¤¯à¤¾ à¤†à¤ª à¤µà¤¾à¤•à¤ˆ à¤…à¤ªà¤¨à¤¾ à¤–à¤¾à¤¤à¤¾ à¤¹à¤Ÿà¤¾à¤¨à¤¾ à¤šà¤¾à¤¹à¤¤à¥‡ à¤¹à¥ˆà¤‚? à¤¯à¤¹ à¤•à¥à¤°à¤¿à¤¯à¤¾ à¤…à¤ªà¤°à¤¿à¤µà¤°à¥à¤¤à¤¨à¥€à¤¯ à¤¹à¥ˆà¥¤',
      'Delete': 'à¤¹à¤Ÿà¤¾à¤à¤‚',
      'Account deleted successfully.': 'à¤–à¤¾à¤¤à¤¾ à¤¸à¤«à¤²à¤¤à¤¾à¤ªà¥‚à¤°à¥à¤µà¤• à¤¹à¤Ÿà¤¾à¤¯à¤¾ à¤—à¤¯à¤¾à¥¤',
      'Delete failed': 'à¤¹à¤Ÿà¤¾à¤¨à¤¾ à¤µà¤¿à¤«à¤² à¤¹à¥à¤†',
      'Server error: {error}': 'à¤¸à¤°à¥à¤µà¤° à¤¤à¥à¤°à¥à¤Ÿà¤¿: {error}',
      'City not set': 'à¤¶à¤¹à¤° à¤¸à¥‡à¤Ÿ à¤¨à¤¹à¥€à¤‚ à¤¹à¥ˆ',
      'India': 'à¤­à¤¾à¤°à¤¤',
      'Edit Profile': 'à¤ªà¥à¤°à¥‹à¤«à¤¾à¤‡à¤² à¤¸à¤‚à¤ªà¤¾à¤¦à¤¿à¤¤ à¤•à¤°à¥‡à¤‚',
      'Profile Completeness': 'à¤ªà¥à¤°à¥‹à¤«à¤¾à¤‡à¤² à¤ªà¥‚à¤°à¥à¤£à¤¤à¤¾',
      '{percent}% complete': '{percent}% à¤ªà¥‚à¤°à¥à¤£',
      'Missing: {items}': 'à¤…à¤ªà¥‚à¤°à¥à¤£: {items}',
      'Impact Summary': 'à¤ªà¥à¤°à¤­à¤¾à¤µ à¤¸à¤¾à¤°à¤¾à¤‚à¤¶',
      'Rating': 'à¤°à¥‡à¤Ÿà¤¿à¤‚à¤—',
      'My Applications': 'à¤®à¥‡à¤°à¥‡ à¤†à¤µà¥‡à¤¦à¤¨',
      'Saved Events': 'à¤¸à¥‡à¤µ à¤•à¤¿à¤ à¤—à¤ à¤‡à¤µà¥‡à¤‚à¤Ÿà¥à¤¸',
      'My Badges': 'à¤®à¥‡à¤°à¥‡ à¤¬à¥ˆà¤œ',
      'Verification Under Review': 'à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¨ à¤¸à¤®à¥€à¤•à¥à¤·à¤¾ à¤®à¥‡à¤‚ à¤¹à¥ˆ',
      'Verified': 'à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¿à¤¤',
      'Get Verified': 'à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¨ à¤ªà¥à¤°à¤¾à¤ªà¥à¤¤ à¤•à¤°à¥‡à¤‚',
      'Your account is already verified.': 'à¤†à¤ªà¤•à¤¾ à¤–à¤¾à¤¤à¤¾ à¤ªà¤¹à¤²à¥‡ à¤¸à¥‡ à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¿à¤¤ à¤¹à¥ˆà¥¤',
      'Your verification request is under review.':
          'à¤†à¤ªà¤•à¤¾ à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¨ à¤…à¤¨à¥à¤°à¥‹à¤§ à¤¸à¤®à¥€à¤•à¥à¤·à¤¾ à¤®à¥‡à¤‚ à¤¹à¥ˆà¥¤',
      'Payment Status': 'à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤¸à¥à¤¥à¤¿à¤¤à¤¿',
      'Invite Friends': 'à¤®à¤¿à¤¤à¥à¤°à¥‹à¤‚ à¤•à¥‹ à¤†à¤®à¤‚à¤¤à¥à¤°à¤¿à¤¤ à¤•à¤°à¥‡à¤‚',
      'Edit': 'à¤¸à¤‚à¤ªà¤¾à¤¦à¤¿à¤¤ à¤•à¤°à¥‡à¤‚',
      'Only JPG, JPEG, PNG, and WEBP images are allowed':
          'à¤•à¥‡à¤µà¤² JPG, JPEG, PNG à¤”à¤° WEBP à¤‡à¤®à¥‡à¤œ à¤…à¤¨à¥à¤®à¤¤ à¤¹à¥ˆà¤‚',
      'Image must be 5 MB or smaller':
          'à¤‡à¤®à¥‡à¤œ 5 MB à¤¯à¤¾ à¤‰à¤¸à¤¸à¥‡ à¤•à¤® à¤¹à¥‹à¤¨à¥€ à¤šà¤¾à¤¹à¤¿à¤',
      'Error picking image: {error}': 'à¤‡à¤®à¥‡à¤œ à¤šà¥à¤¨à¤¨à¥‡ à¤®à¥‡à¤‚ à¤¤à¥à¤°à¥à¤Ÿà¤¿: {error}',
      'Profile picture updated successfully':
          'à¤ªà¥à¤°à¥‹à¤«à¤¾à¤‡à¤² à¤¤à¤¸à¥à¤µà¥€à¤° à¤¸à¤«à¤²à¤¤à¤¾à¤ªà¥‚à¤°à¥à¤µà¤• à¤…à¤ªà¤¡à¥‡à¤Ÿ à¤¹à¥à¤ˆ',
      'Failed to upload image': 'à¤‡à¤®à¥‡à¤œ à¤…à¤ªà¤²à¥‹à¤¡ à¤µà¤¿à¤«à¤²',
      'Remove Profile Picture': 'à¤ªà¥à¤°à¥‹à¤«à¤¾à¤‡à¤² à¤¤à¤¸à¥à¤µà¥€à¤° à¤¹à¤Ÿà¤¾à¤à¤‚',
      'Are you sure you want to remove your profile picture?':
          'à¤•à¥à¤¯à¤¾ à¤†à¤ª à¤µà¤¾à¤•à¤ˆ à¤…à¤ªà¤¨à¥€ à¤ªà¥à¤°à¥‹à¤«à¤¾à¤‡à¤² à¤¤à¤¸à¥à¤µà¥€à¤° à¤¹à¤Ÿà¤¾à¤¨à¤¾ à¤šà¤¾à¤¹à¤¤à¥‡ à¤¹à¥ˆà¤‚?',
      'Remove': 'à¤¹à¤Ÿà¤¾à¤à¤‚',
      'Profile picture removed successfully':
          'à¤ªà¥à¤°à¥‹à¤«à¤¾à¤‡à¤² à¤¤à¤¸à¥à¤µà¥€à¤° à¤¸à¤«à¤²à¤¤à¤¾à¤ªà¥‚à¤°à¥à¤µà¤• à¤¹à¤Ÿà¤¾à¤ˆ à¤—à¤ˆ',
      'Failed to remove picture': 'à¤¤à¤¸à¥à¤µà¥€à¤° à¤¹à¤Ÿà¤¾à¤¨à¥‡ à¤®à¥‡à¤‚ à¤µà¤¿à¤«à¤²',
      'Name cannot be empty': 'à¤¨à¤¾à¤® à¤–à¤¾à¤²à¥€ à¤¨à¤¹à¥€à¤‚ à¤¹à¥‹ à¤¸à¤•à¤¤à¤¾',
      'Profile updated, but preferences failed':
          'à¤ªà¥à¤°à¥‹à¤«à¤¾à¤‡à¤² à¤…à¤ªà¤¡à¥‡à¤Ÿ à¤¹à¥à¤ˆ, à¤²à¥‡à¤•à¤¿à¤¨ à¤ªà¥à¤°à¤¾à¤¥à¤®à¤¿à¤•à¤¤à¤¾à¤à¤‚ à¤¸à¤¹à¥‡à¤œà¤¨à¥‡ à¤®à¥‡à¤‚ à¤µà¤¿à¤«à¤²',
      'Profile updated successfully': 'à¤ªà¥à¤°à¥‹à¤«à¤¾à¤‡à¤² à¤¸à¤«à¤²à¤¤à¤¾à¤ªà¥‚à¤°à¥à¤µà¤• à¤…à¤ªà¤¡à¥‡à¤Ÿ à¤¹à¥à¤ˆ',
      'Update failed: {message}': 'à¤…à¤ªà¤¡à¥‡à¤Ÿ à¤µà¤¿à¤«à¤²: {message}',
      'Change Profile Picture': 'à¤ªà¥à¤°à¥‹à¤«à¤¾à¤‡à¤² à¤¤à¤¸à¥à¤µà¥€à¤° à¤¬à¤¦à¤²à¥‡à¤‚',
      'Full Name': 'à¤ªà¥‚à¤°à¤¾ à¤¨à¤¾à¤®',
      'City (Optional)': 'à¤¶à¤¹à¤° (à¤µà¥ˆà¤•à¤²à¥à¤ªà¤¿à¤•)',
      'Contact Number (Optional)': 'à¤¸à¤‚à¤ªà¤°à¥à¤• à¤¨à¤‚à¤¬à¤° (à¤µà¥ˆà¤•à¤²à¥à¤ªà¤¿à¤•)',
      'Skills': 'à¤•à¥Œà¤¶à¤²',
      'Add skill': 'à¤•à¥Œà¤¶à¤² à¤œà¥‹à¤¡à¤¼à¥‡à¤‚',
      'Interests': 'à¤°à¥à¤šà¤¿à¤¯à¤¾à¤‚',
      'Add interest': 'à¤°à¥à¤šà¤¿ à¤œà¥‹à¤¡à¤¼à¥‡à¤‚',
      'Saving...': 'à¤¸à¤¹à¥‡à¤œà¤¾ à¤œà¤¾ à¤°à¤¹à¤¾ à¤¹à¥ˆ...',
      'Save Changes': 'à¤ªà¤°à¤¿à¤µà¤°à¥à¤¤à¤¨ à¤¸à¤¹à¥‡à¤œà¥‡à¤‚',
      'No items added': 'à¤•à¥‹à¤ˆ à¤†à¤‡à¤Ÿà¤® à¤œà¥‹à¤¡à¤¼à¤¾ à¤¨à¤¹à¥€à¤‚ à¤—à¤¯à¤¾',
      'Unable to load badges right now.':
          'à¤…à¤­à¥€ à¤¬à¥ˆà¤œ à¤²à¥‹à¤¡ à¤¨à¤¹à¥€à¤‚ à¤¹à¥‹ à¤°à¤¹à¥‡ à¤¹à¥ˆà¤‚à¥¤',
      'hosted events': 'à¤†à¤¯à¥‹à¤œà¤¿à¤¤ à¤‡à¤µà¥‡à¤‚à¤Ÿà¥à¤¸',
      'completed events': 'à¤ªà¥‚à¤°à¥à¤£ à¤•à¤¿à¤ à¤—à¤ à¤‡à¤µà¥‡à¤‚à¤Ÿà¥à¤¸',
      'Requires {threshold} {noun}': 'à¤†à¤µà¤¶à¥à¤¯à¤•: {threshold} {noun}',
      'Hosted events': 'à¤†à¤¯à¥‹à¤œà¤¿à¤¤ à¤‡à¤µà¥‡à¤‚à¤Ÿà¥à¤¸',
      'Completed events': 'à¤ªà¥‚à¤°à¥à¤£ à¤•à¤¿à¤ à¤—à¤ à¤‡à¤µà¥‡à¤‚à¤Ÿà¥à¤¸',
      'No badge yet': 'à¤…à¤­à¥€ à¤•à¥‹à¤ˆ à¤¬à¥ˆà¤œ à¤¨à¤¹à¥€à¤‚',
      'Refresh': 'à¤°à¤¿à¤«à¥à¤°à¥‡à¤¶',
      'Current Badge: {badge}': 'à¤µà¤°à¥à¤¤à¤®à¤¾à¤¨ à¤¬à¥ˆà¤œ: {badge}',
      '{label}: {count}': '{label}: {count}',
      'Next badge: {name} at {threshold} {label}':
          'à¤…à¤—à¤²à¤¾ à¤¬à¥ˆà¤œ: {name} {threshold} {label} à¤ªà¤°',
      'No badges configured in system yet.':
          'à¤¸à¤¿à¤¸à¥à¤Ÿà¤® à¤®à¥‡à¤‚ à¤…à¤­à¥€ à¤•à¥‹à¤ˆ à¤¬à¥ˆà¤œ à¤•à¥‰à¤¨à¥à¤«à¤¼à¤¿à¤—à¤° à¤¨à¤¹à¥€à¤‚ à¤¹à¥ˆà¥¤',
      'Badge': 'à¤¬à¥ˆà¤œ',
      'Status updated': 'à¤¸à¥à¤¥à¤¿à¤¤à¤¿ à¤…à¤ªà¤¡à¥‡à¤Ÿ à¤¹à¥à¤ˆ',
      'Failed: {message}': 'à¤µà¤¿à¤«à¤²: {message}',
      'Failed to update status': 'à¤¸à¥à¤¥à¤¿à¤¤à¤¿ à¤…à¤ªà¤¡à¥‡à¤Ÿ à¤•à¤°à¤¨à¥‡ à¤®à¥‡à¤‚ à¤µà¤¿à¤«à¤²',
      'Received': 'à¤ªà¥à¤°à¤¾à¤ªà¥à¤¤',
      'Not applicable': 'à¤²à¤¾à¤—à¥‚ à¤¨à¤¹à¥€à¤‚',
      'Payment report details are not available.':
          'à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤°à¤¿à¤ªà¥‹à¤°à¥à¤Ÿ à¤µà¤¿à¤µà¤°à¤£ à¤‰à¤ªà¤²à¤¬à¥à¤§ à¤¨à¤¹à¥€à¤‚ à¤¹à¥ˆà¤‚à¥¤',
      'This unpaid payment report was already submitted.':
          'à¤¯à¤¹ à¤…à¤ªà¥à¤°à¤¾à¤ªà¥à¤¤ à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤°à¤¿à¤ªà¥‹à¤°à¥à¤Ÿ à¤ªà¤¹à¤²à¥‡ à¤¹à¥€ à¤¸à¤¬à¤®à¤¿à¤Ÿ à¤•à¥€ à¤œà¤¾ à¤šà¥à¤•à¥€ à¤¹à¥ˆà¥¤',
      'Report Unpaid Payment': 'à¤…à¤ªà¥à¤°à¤¾à¤ªà¥à¤¤ à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤°à¤¿à¤ªà¥‹à¤°à¥à¤Ÿ à¤•à¤°à¥‡à¤‚',
      'This will create an admin report for unpaid compensation on {event}.':
          '{event} à¤•à¥‡ à¤²à¤¿à¤ à¤…à¤ªà¥à¤°à¤¾à¤ªà¥à¤¤ à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤ªà¤° à¤¯à¤¹ à¤à¤• à¤à¤¡à¤®à¤¿à¤¨ à¤°à¤¿à¤ªà¥‹à¤°à¥à¤Ÿ à¤¬à¤¨à¤¾à¤à¤—à¤¾à¥¤',
      'this event': 'à¤‡à¤¸ à¤‡à¤µà¥‡à¤‚à¤Ÿ',
      'Details': 'à¤µà¤¿à¤µà¤°à¤£',
      'Add any payment issue details for admin review.':
          'à¤à¤¡à¤®à¤¿à¤¨ à¤¸à¤®à¥€à¤•à¥à¤·à¤¾ à¤•à¥‡ à¤²à¤¿à¤ à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤¸à¤®à¤¸à¥à¤¯à¤¾ à¤•à¤¾ à¤µà¤¿à¤µà¤°à¤£ à¤œà¥‹à¤¡à¤¼à¥‡à¤‚à¥¤',
      'Please add a short note for admin review.':
          'à¤à¤¡à¤®à¤¿à¤¨ à¤¸à¤®à¥€à¤•à¥à¤·à¤¾ à¤•à¥‡ à¤²à¤¿à¤ à¤›à¥‹à¤Ÿà¤¾ à¤¨à¥‹à¤Ÿ à¤œà¥‹à¤¡à¤¼à¥‡à¤‚à¥¤',
      'Submit Report': 'à¤°à¤¿à¤ªà¥‹à¤°à¥à¤Ÿ à¤¸à¤¬à¤®à¤¿à¤Ÿ à¤•à¤°à¥‡à¤‚',
      'Unknown event': 'à¤…à¤œà¥à¤žà¤¾à¤¤ à¤‡à¤µà¥‡à¤‚à¤Ÿ',
      'Paid event': 'à¤ªà¥‡à¤¡ à¤‡à¤µà¥‡à¤‚à¤Ÿ',
      'Unpaid payment report submitted for admin review.':
          'à¤…à¤ªà¥à¤°à¤¾à¤ªà¥à¤¤ à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤°à¤¿à¤ªà¥‹à¤°à¥à¤Ÿ à¤à¤¡à¤®à¤¿à¤¨ à¤¸à¤®à¥€à¤•à¥à¤·à¤¾ à¤•à¥‡ à¤²à¤¿à¤ à¤¸à¤¬à¤®à¤¿à¤Ÿ à¤•à¥€ à¤—à¤ˆà¥¤',
      'Failed to submit report: {error}':
          'à¤°à¤¿à¤ªà¥‹à¤°à¥à¤Ÿ à¤¸à¤¬à¤®à¤¿à¤Ÿ à¤•à¤°à¤¨à¥‡ à¤®à¥‡à¤‚ à¤µà¤¿à¤«à¤²: {error}',
      'No approved events yet': 'à¤…à¤­à¥€ à¤¤à¤• à¤•à¥‹à¤ˆ à¤¸à¥à¤µà¥€à¤•à¥ƒà¤¤ à¤‡à¤µà¥‡à¤‚à¤Ÿ à¤¨à¤¹à¥€à¤‚',
      'Unknown Event': 'à¤…à¤œà¥à¤žà¤¾à¤¤ à¤‡à¤µà¥‡à¤‚à¤Ÿ',
      'Unpaid payment report submitted.': 'à¤…à¤ªà¥à¤°à¤¾à¤ªà¥à¤¤ à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤°à¤¿à¤ªà¥‹à¤°à¥à¤Ÿ à¤¸à¤¬à¤®à¤¿à¤Ÿ à¤•à¥€ à¤—à¤ˆà¥¤',
      'Payment is still pending after clearance date.':
          'à¤•à¥à¤²à¥€à¤¯à¤°à¥‡à¤‚à¤¸ à¤¡à¥‡à¤Ÿ à¤•à¥‡ à¤¬à¤¾à¤¦ à¤­à¥€ à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤²à¤‚à¤¬à¤¿à¤¤ à¤¹à¥ˆà¥¤',
      'Reported': 'à¤°à¤¿à¤ªà¥‹à¤°à¥à¤Ÿ à¤•à¤¿à¤¯à¤¾ à¤—à¤¯à¤¾',
      'Report unpaid payment': 'à¤…à¤ªà¥à¤°à¤¾à¤ªà¥à¤¤ à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤°à¤¿à¤ªà¥‹à¤°à¥à¤Ÿ à¤•à¤°à¥‡à¤‚',
      'Please login again to view organiser details.':
          'à¤†à¤¯à¥‹à¤œà¤• à¤µà¤¿à¤µà¤°à¤£ à¤¦à¥‡à¤–à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ à¤•à¥ƒà¤ªà¤¯à¤¾ à¤«à¤¿à¤° à¤¸à¥‡ à¤²à¥‰à¤—à¤¿à¤¨ à¤•à¤°à¥‡à¤‚à¥¤',
      'Failed to load organiser profile': 'à¤†à¤¯à¥‹à¤œà¤• à¤ªà¥à¤°à¥‹à¤«à¤¼à¤¾à¤‡à¤² à¤²à¥‹à¤¡ à¤•à¤°à¤¨à¥‡ à¤®à¥‡à¤‚ à¤µà¤¿à¤«à¤²',
      'Network error': 'à¤¨à¥‡à¤Ÿà¤µà¤°à¥à¤• à¤¤à¥à¤°à¥à¤Ÿà¤¿',
      'Organiser': 'à¤†à¤¯à¥‹à¤œà¤•',
      'Organiser Profile': 'à¤†à¤¯à¥‹à¤œà¤• à¤ªà¥à¤°à¥‹à¤«à¤¼à¤¾à¤‡à¤²',
      'About Organisation': 'à¤¸à¤‚à¤—à¤ à¤¨ à¤•à¥‡ à¤¬à¤¾à¤°à¥‡ à¤®à¥‡à¤‚',
      'No description provided by organiser.':
          'à¤†à¤¯à¥‹à¤œà¤• à¤¦à¥à¤µà¤¾à¤°à¤¾ à¤•à¥‹à¤ˆ à¤µà¤¿à¤µà¤°à¤£ à¤‰à¤ªà¤²à¤¬à¥à¤§ à¤¨à¤¹à¥€à¤‚ à¤•à¤°à¤¾à¤¯à¤¾ à¤—à¤¯à¤¾à¥¤',
      'Based in {city}.': '{city} à¤®à¥‡à¤‚ à¤¸à¥à¤¥à¤¿à¤¤à¥¤',
      'Volunteers': 'à¤¸à¥à¤µà¤¯à¤‚à¤¸à¥‡à¤µà¤•',
      'Connect with Us': 'à¤¹à¤®à¤¸à¥‡ à¤œà¥à¤¡à¤¼à¥‡à¤‚',
      'Follow or visit to learn more about their work':
          'à¤‰à¤¨à¤•à¥‡ à¤•à¤¾à¤°à¥à¤¯ à¤•à¥‡ à¤¬à¤¾à¤°à¥‡ à¤®à¥‡à¤‚ à¤…à¤§à¤¿à¤• à¤œà¤¾à¤¨à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ à¤«à¥‰à¤²à¥‹ à¤•à¤°à¥‡à¤‚ à¤¯à¤¾ à¤µà¤¿à¤œà¤¼à¤¿à¤Ÿ à¤•à¤°à¥‡à¤‚',
      'Website': 'à¤µà¥‡à¤¬à¤¸à¤¾à¤‡à¤Ÿ',
      'Instagram': 'à¤‡à¤‚à¤¸à¥à¤Ÿà¤¾à¤—à¥à¤°à¤¾à¤®',
      'Facebook': 'à¤«à¥‡à¤¸à¤¬à¥à¤•',
      'LinkedIn': 'à¤²à¤¿à¤‚à¤•à¥à¤¡à¤‡à¤¨',
      'Phone number is available only to approved volunteers when the organiser enables sharing.':
          'à¤†à¤¯à¥‹à¤œà¤• à¤¦à¥à¤µà¤¾à¤°à¤¾ à¤¶à¥‡à¤¯à¤°à¤¿à¤‚à¤— à¤¸à¤•à¥à¤·à¤® à¤•à¤°à¤¨à¥‡ à¤ªà¤° à¤«à¥‹à¤¨ à¤¨à¤‚à¤¬à¤° à¤•à¥‡à¤µà¤² à¤¸à¥à¤µà¥€à¤•à¥ƒà¤¤ à¤¸à¥à¤µà¤¯à¤‚à¤¸à¥‡à¤µà¤•à¥‹à¤‚ à¤•à¥‹ à¤¦à¤¿à¤–à¤¾à¤ˆ à¤¦à¥‡à¤—à¤¾à¥¤',
      'Volunteer Reviews': 'à¤¸à¥à¤µà¤¯à¤‚à¤¸à¥‡à¤µà¤• à¤¸à¤®à¥€à¤•à¥à¤·à¤¾à¤à¤‚',
      'No reviews yet': 'à¤…à¤­à¥€ à¤¤à¤• à¤•à¥‹à¤ˆ à¤¸à¤®à¥€à¤•à¥à¤·à¤¾ à¤¨à¤¹à¥€à¤‚',
      'Anonymous': 'à¤…à¤¨à¤¾à¤®',
      'View All {count} Reviews': 'à¤¸à¤­à¥€ {count} à¤¸à¤®à¥€à¤•à¥à¤·à¤¾à¤à¤‚ à¤¦à¥‡à¤–à¥‡à¤‚',
      'All Reviews': 'à¤¸à¤­à¥€ à¤¸à¤®à¥€à¤•à¥à¤·à¤¾à¤à¤‚',
      'Last 5 Events Overall Rating': 'à¤ªà¤¿à¤›à¤²à¥‡ 5 à¤‡à¤µà¥‡à¤‚à¤Ÿà¥à¤¸ à¤•à¥€ à¤•à¥à¤² à¤°à¥‡à¤Ÿà¤¿à¤‚à¤—',
      'Unknown': 'à¤…à¤œà¥à¤žà¤¾à¤¤',
      'Individual Reviews': 'à¤µà¥à¤¯à¤•à¥à¤¤à¤¿à¤—à¤¤ à¤¸à¤®à¥€à¤•à¥à¤·à¤¾à¤à¤‚',
      '{count} reviews': '{count} à¤¸à¤®à¥€à¤•à¥à¤·à¤¾à¤à¤‚',
      'No leaderboard data available': 'à¤²à¥€à¤¡à¤°à¤¬à¥‹à¤°à¥à¤¡ à¤¡à¥‡à¤Ÿà¤¾ à¤‰à¤ªà¤²à¤¬à¥à¤§ à¤¨à¤¹à¥€à¤‚ à¤¹à¥ˆ',
      'Failed to load leaderboard': 'à¤²à¥€à¤¡à¤°à¤¬à¥‹à¤°à¥à¤¡ à¤²à¥‹à¤¡ à¤•à¤°à¤¨à¥‡ à¤®à¥‡à¤‚ à¤µà¤¿à¤«à¤²',
      'Organisers': 'à¤†à¤¯à¥‹à¤œà¤•',
      'Weekly': 'à¤¸à¤¾à¤ªà¥à¤¤à¤¾à¤¹à¤¿à¤•',
      'Monthly': 'à¤®à¤¾à¤¸à¤¿à¤•',
      '{count} events': '{count} à¤‡à¤µà¥‡à¤‚à¤Ÿà¥à¤¸',
      '{count} events completed': '{count} à¤‡à¤µà¥‡à¤‚à¤Ÿà¥à¤¸ à¤ªà¥‚à¤°à¥à¤£ à¤•à¤¿à¤',
      'Announcements': 'à¤˜à¥‹à¤·à¤£à¤¾à¤à¤‚',
      'Failed to load announcements\n{error}':
          'à¤˜à¥‹à¤·à¤£à¤¾à¤à¤‚ à¤²à¥‹à¤¡ à¤•à¤°à¤¨à¥‡ à¤®à¥‡à¤‚ à¤µà¤¿à¤«à¤²\n{error}',
      'No announcements for {event}': '{event} à¤•à¥‡ à¤²à¤¿à¤ à¤•à¥‹à¤ˆ à¤˜à¥‹à¤·à¤£à¤¾ à¤¨à¤¹à¥€à¤‚',
      'Announcement': 'à¤˜à¥‹à¤·à¤£à¤¾',
      'Please login again': 'à¤•à¥ƒà¤ªà¤¯à¤¾ à¤«à¤¿à¤° à¤¸à¥‡ à¤²à¥‰à¤—à¤¿à¤¨ à¤•à¤°à¥‡à¤‚',
      'Please upload ID proof': 'à¤•à¥ƒà¤ªà¤¯à¤¾ à¤†à¤ˆà¤¡à¥€ à¤ªà¥à¤°à¤®à¤¾à¤£ à¤…à¤ªà¤²à¥‹à¤¡ à¤•à¤°à¥‡à¤‚',
      'Please upload selfie with ID': 'à¤•à¥ƒà¤ªà¤¯à¤¾ à¤†à¤ˆà¤¡à¥€ à¤•à¥‡ à¤¸à¤¾à¤¥ à¤¸à¥‡à¤²à¥à¤«à¥€ à¤…à¤ªà¤²à¥‹à¤¡ à¤•à¤°à¥‡à¤‚',
      'Verification request submitted': 'à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¨ à¤…à¤¨à¥à¤°à¥‹à¤§ à¤¸à¤¬à¤®à¤¿à¤Ÿ à¤•à¤¿à¤¯à¤¾ à¤—à¤¯à¤¾',
      'Submission failed': 'à¤¸à¤¬à¤®à¤¿à¤¶à¤¨ à¤µà¤¿à¤«à¤²',
      'You do not need to submit verification again.':
          'à¤†à¤ªà¤•à¥‹ à¤«à¤¿à¤° à¤¸à¥‡ à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¨ à¤¸à¤¬à¤®à¤¿à¤Ÿ à¤•à¤°à¤¨à¥‡ à¤•à¥€ à¤†à¤µà¤¶à¥à¤¯à¤•à¤¤à¤¾ à¤¨à¤¹à¥€à¤‚ à¤¹à¥ˆà¥¤',
      'Back to Profile': 'à¤ªà¥à¤°à¥‹à¤«à¤¾à¤‡à¤² à¤ªà¤° à¤µà¤¾à¤ªà¤¸',
      'You cannot submit another request until the current one is reviewed.':
          'à¤µà¤°à¥à¤¤à¤®à¤¾à¤¨ à¤…à¤¨à¥à¤°à¥‹à¤§ à¤•à¥€ à¤¸à¤®à¥€à¤•à¥à¤·à¤¾ à¤¹à¥‹à¤¨à¥‡ à¤¤à¤• à¤†à¤ª à¤¦à¥‚à¤¸à¤°à¤¾ à¤…à¤¨à¥à¤°à¥‹à¤§ à¤¸à¤¬à¤®à¤¿à¤Ÿ à¤¨à¤¹à¥€à¤‚ à¤•à¤° à¤¸à¤•à¤¤à¥‡à¥¤',
      'Your previous verification request was rejected. Please review your details and submit again.':
          'à¤†à¤ªà¤•à¤¾ à¤ªà¤¿à¤›à¤²à¤¾ à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¨ à¤…à¤¨à¥à¤°à¥‹à¤§ à¤…à¤¸à¥à¤µà¥€à¤•à¥ƒà¤¤ à¤¹à¥à¤† à¤¥à¤¾à¥¤ à¤•à¥ƒà¤ªà¤¯à¤¾ à¤µà¤¿à¤µà¤°à¤£ à¤œà¤¾à¤‚à¤šà¥‡à¤‚ à¤”à¤° à¤«à¤¿à¤° à¤¸à¥‡ à¤¸à¤¬à¤®à¤¿à¤Ÿ à¤•à¤°à¥‡à¤‚à¥¤',
      'Volunteer Verification': 'à¤¸à¥à¤µà¤¯à¤‚à¤¸à¥‡à¤µà¤• à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¨',
      'ID Type': 'à¤†à¤ˆà¤¡à¥€ à¤ªà¥à¤°à¤•à¤¾à¤°',
      'Please select ID type': 'à¤•à¥ƒà¤ªà¤¯à¤¾ à¤†à¤ˆà¤¡à¥€ à¤ªà¥à¤°à¤•à¤¾à¤° à¤šà¥à¤¨à¥‡à¤‚',
      'Upload ID Proof *': 'à¤†à¤ˆà¤¡à¥€ à¤ªà¥à¤°à¤®à¤¾à¤£ à¤…à¤ªà¤²à¥‹à¤¡ à¤•à¤°à¥‡à¤‚ *',
      'ID Selected': 'à¤†à¤ˆà¤¡à¥€ à¤šà¤¯à¤¨à¤¿à¤¤',
      'File too large (max 5MB)': 'à¤«à¤¼à¤¾à¤‡à¤² à¤¬à¤¹à¥à¤¤ à¤¬à¤¡à¤¼à¥€ à¤¹à¥ˆ (à¤…à¤§à¤¿à¤•à¤¤à¤® 5MB)',
      'Uploading ID proof...': 'à¤†à¤ˆà¤¡à¥€ à¤ªà¥à¤°à¤®à¤¾à¤£ à¤…à¤ªà¤²à¥‹à¤¡ à¤¹à¥‹ à¤°à¤¹à¤¾ à¤¹à¥ˆ...',
      'ID proof uploaded': 'à¤†à¤ˆà¤¡à¥€ à¤ªà¥à¤°à¤®à¤¾à¤£ à¤…à¤ªà¤²à¥‹à¤¡ à¤¹à¥‹ à¤—à¤¯à¤¾',
      'Upload failed: {error}': 'à¤…à¤ªà¤²à¥‹à¤¡ à¤µà¤¿à¤«à¤²: {error}',
      'Upload Selfie with ID *': 'à¤†à¤ˆà¤¡à¥€ à¤•à¥‡ à¤¸à¤¾à¤¥ à¤¸à¥‡à¤²à¥à¤«à¥€ à¤…à¤ªà¤²à¥‹à¤¡ à¤•à¤°à¥‡à¤‚ *',
      'Selfie Selected': 'à¤¸à¥‡à¤²à¥à¤«à¥€ à¤šà¤¯à¤¨à¤¿à¤¤',
      'Uploading selfie...': 'à¤¸à¥‡à¤²à¥à¤«à¥€ à¤…à¤ªà¤²à¥‹à¤¡ à¤¹à¥‹ à¤°à¤¹à¥€ à¤¹à¥ˆ...',
      'Selfie uploaded': 'à¤¸à¥‡à¤²à¥à¤«à¥€ à¤…à¤ªà¤²à¥‹à¤¡ à¤¹à¥‹ à¤—à¤ˆ',
      'ID Number': 'à¤†à¤ˆà¤¡à¥€ à¤¨à¤‚à¤¬à¤°',
      'Enter ID number': 'à¤†à¤ˆà¤¡à¥€ à¤¨à¤‚à¤¬à¤° à¤¦à¤°à¥à¤œ à¤•à¤°à¥‡à¤‚',
      'Invalid ID number': 'à¤…à¤®à¤¾à¤¨à¥à¤¯ à¤†à¤ˆà¤¡à¥€ à¤¨à¤‚à¤¬à¤°',
      'Submit for Verification': 'à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¨ à¤•à¥‡ à¤²à¤¿à¤ à¤¸à¤¬à¤®à¤¿à¤Ÿ à¤•à¤°à¥‡à¤‚',
      'Invite friends to VolunteerX': 'VolunteerX à¤®à¥‡à¤‚ à¤¦à¥‹à¤¸à¥à¤¤à¥‹à¤‚ à¤•à¥‹ à¤†à¤®à¤‚à¤¤à¥à¤°à¤¿à¤¤ à¤•à¤°à¥‡à¤‚',
      'Volunteer together, earn badges faster!':
          'à¤¸à¤¾à¤¥ à¤®à¤¿à¤²à¤•à¤° à¤¸à¥à¤µà¤¯à¤‚à¤¸à¥‡à¤µà¤¾ à¤•à¤°à¥‡à¤‚, à¤¤à¥‡à¤œà¥€ à¤¸à¥‡ à¤¬à¥ˆà¤œ à¤ªà¤¾à¤à¤‚!',
      'Share Invite Link': 'à¤‡à¤¨à¤µà¤¾à¤‡à¤Ÿ à¤²à¤¿à¤‚à¤• à¤¸à¤¾à¤à¤¾ à¤•à¤°à¥‡à¤‚',
      'Removed': 'à¤¹à¤Ÿà¤¾à¤¯à¤¾ à¤—à¤¯à¤¾',
      'Date not set': 'à¤¤à¤¾à¤°à¥€à¤– à¤¨à¤¿à¤°à¥à¤§à¤¾à¤°à¤¿à¤¤ à¤¨à¤¹à¥€à¤‚ à¤¹à¥ˆ',
      'Your Organisation': 'à¤†à¤ªà¤•à¤¾ à¤¸à¤‚à¤—à¤ à¤¨',
      'Reviews': 'à¤¸à¤®à¥€à¤•à¥à¤·à¤¾à¤à¤‚',
      'Your volunteers will appear here':
          'à¤†à¤ªà¤•à¥‡ à¤¸à¥à¤µà¤¯à¤‚à¤¸à¥‡à¤µà¤• à¤¯à¤¹à¤¾à¤‚ à¤¦à¤¿à¤–à¤¾à¤ˆ à¤¦à¥‡à¤‚à¤—à¥‡',
      'No events found': 'à¤•à¥‹à¤ˆ à¤‡à¤µà¥‡à¤‚à¤Ÿ à¤¨à¤¹à¥€à¤‚ à¤®à¤¿à¤²à¤¾',
      'Untitled Event': 'à¤¶à¥€à¤°à¥à¤·à¤•à¤¹à¥€à¤¨ à¤‡à¤µà¥‡à¤‚à¤Ÿ',
      'Location not set': 'à¤¸à¥à¤¥à¤¾à¤¨ à¤¨à¤¿à¤°à¥à¤§à¤¾à¤°à¤¿à¤¤ à¤¨à¤¹à¥€à¤‚ à¤¹à¥ˆ',
      'Your organisation rating': 'à¤†à¤ªà¤•à¥‡ à¤¸à¤‚à¤—à¤ à¤¨ à¤•à¥€ à¤°à¥‡à¤Ÿà¤¿à¤‚à¤—',
      'Volunteer reviews will appear here':
          'à¤¸à¥à¤µà¤¯à¤‚à¤¸à¥‡à¤µà¤• à¤¸à¤®à¥€à¤•à¥à¤·à¤¾à¤à¤‚ à¤¯à¤¹à¤¾à¤‚ à¤¦à¤¿à¤–à¤¾à¤ˆ à¤¦à¥‡à¤‚à¤—à¥€',
      'My Events': 'à¤®à¥‡à¤°à¥‡ à¤‡à¤µà¥‡à¤‚à¤Ÿà¥à¤¸',
      'Total': 'à¤•à¥à¤²',
      'Search events...': 'à¤‡à¤µà¥‡à¤‚à¤Ÿà¥à¤¸ à¤–à¥‹à¤œà¥‡à¤‚...',
            'About Volunteerx': 'Volunteerx à¤•à¥‡ à¤¬à¤¾à¤°à¥‡ à¤®à¥‡à¤‚',
            'Account deactivated': 'à¤–à¤¾à¤¤à¤¾ à¤¨à¤¿à¤·à¥à¤•à¥à¤°à¤¿à¤¯ à¤•à¤° à¤¦à¤¿à¤¯à¤¾ à¤—à¤¯à¤¾',
            'Account Settings': 'à¤–à¤¾à¤¤à¤¾ à¤¸à¥‡à¤Ÿà¤¿à¤‚à¤—à¥à¤¸',
            'App Information': 'à¤à¤ª à¤œà¤¾à¤¨à¤•à¤¾à¤°à¥€',
            'App Version': 'à¤à¤ª à¤¸à¤‚à¤¸à¥à¤•à¤°à¤£',
            'Close': 'à¤¬à¤‚à¤¦ à¤•à¤°à¥‡à¤‚',
            'Contact Support': 'à¤¸à¤¹à¤¾à¤¯à¤¤à¤¾ à¤¸à¥‡ à¤¸à¤‚à¤ªà¤°à¥à¤• à¤•à¤°à¥‡à¤‚',
            'Deactivate': 'à¤¨à¤¿à¤·à¥à¤•à¥à¤°à¤¿à¤¯ à¤•à¤°à¥‡à¤‚',
            'Deactivate Account': 'à¤–à¤¾à¤¤à¤¾ à¤¨à¤¿à¤·à¥à¤•à¥à¤°à¤¿à¤¯ à¤•à¤°à¥‡à¤‚',
            'Deactivate failed': 'à¤¨à¤¿à¤·à¥à¤•à¥à¤°à¤¿à¤¯ à¤•à¤°à¤¨à¤¾ à¤µà¤¿à¤«à¤² à¤¹à¥à¤†',
            'Email our support team': 'à¤¹à¤®à¤¾à¤°à¥€ à¤¸à¤¹à¤¾à¤¯à¤¤à¤¾ à¤Ÿà¥€à¤® à¤•à¥‹ à¤ˆà¤®à¥‡à¤² à¤•à¤°à¥‡à¤‚',
            'Find answers to common questions': 'à¤¸à¤¾à¤®à¤¾à¤¨à¥à¤¯ à¤ªà¥à¤°à¤¶à¥à¤¨à¥‹à¤‚ à¤•à¥‡ à¤‰à¤¤à¥à¤¤à¤° à¤–à¥‹à¤œà¥‡à¤‚',
            'How can we help you?': 'à¤¹à¤® à¤†à¤ªà¤•à¥€ à¤•à¥ˆà¤¸à¥‡ à¤®à¤¦à¤¦ à¤•à¤° à¤¸à¤•à¤¤à¥‡ à¤¹à¥ˆà¤‚?',
            'OK': 'à¤ à¥€à¤• à¤¹à¥ˆ',
            'Organisation Activity': 'à¤¸à¤‚à¤—à¤ à¤¨ à¤—à¤¤à¤¿à¤µà¤¿à¤§à¤¿',
            'Report a Problem': 'à¤¸à¤®à¤¸à¥à¤¯à¤¾ à¤•à¥€ à¤°à¤¿à¤ªà¥‹à¤°à¥à¤Ÿ à¤•à¤°à¥‡à¤‚',
            'Support Email': 'à¤¸à¤¹à¤¾à¤¯à¤¤à¤¾ à¤ˆà¤®à¥‡à¤²',
              'Tell us if something isn\'t working':
                  'à¤¯à¤¦à¤¿ à¤•à¥à¤› à¤•à¤¾à¤® à¤¨à¤¹à¥€à¤‚ à¤•à¤° à¤°à¤¹à¤¾ à¤¹à¥ˆ à¤¤à¥‹ à¤¹à¤®à¥‡à¤‚ à¤¬à¤¤à¤¾à¤à¤‚',
            'Volunteer Details': 'à¤¸à¥à¤µà¤¯à¤‚à¤¸à¥‡à¤µà¤• à¤µà¤¿à¤µà¤°à¤£',
            'Volunteerx Team': 'Volunteerx à¤Ÿà¥€à¤®',
      '99+': '99+',
      'Aadhaar': 'Aadhaar',
      'About VolunteerX': 'About VolunteerX',
      'Absent': 'Absent',
      'Add responsibility': 'Add responsibility',
      'Added to shortlist': 'Added to shortlist',
      'Shortlist is closed for this event.':
          'à¤‡à¤¸ à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤® à¤•à¥‡ à¤²à¤¿à¤ à¤¶à¥‰à¤°à¥à¤Ÿà¤²à¤¿à¤¸à¥à¤Ÿ à¤…à¤¬ à¤¬à¤‚à¤¦ à¤¹à¥ˆà¥¤',
      'Announce': 'Announce',
      'Announcement sent. No volunteers to notify yet.': 'Announcement sent. No volunteers to notify yet.',
      'Application Deadline': 'Application Deadline',
      'Applied': 'Applied',
      'Attendance': 'Attendance',
      'Attendance saved': 'Attendance saved',
      'Available': 'Available',
      'Back': 'Back',
      'Badges': 'Badges',
      'Basic Details': 'Basic Details',
      'Cancel Event': 'Cancel Event',
      'Cancelled by organiser/admin': 'Cancelled by organiser/admin',
      'Cancelled by volunteer': 'Cancelled by volunteer',
      'Cannot approve. Slots are full.': 'Cannot approve. Slots are full.',
      'Categories': 'Categories',
      'Category': 'Category',
      'Change Password': 'Change Password',
      'Chat': 'Chat',
      'Chat info not available': 'Chat info not available',
      'Confirm': 'Confirm',
      'Confirm cancellation': 'Confirm cancellation',
      'Please review details before cancelling this event.':
          'Please review details before cancelling this event.',
      'Event: {title}': 'Event: {title}',
      'Reason: {reason}': 'Reason: {reason}',
      'Confirm New Password': 'Confirm New Password',
      'Contact Number': 'Contact Number',
      'Copyright 2026 VolunteerX. All rights reserved.': 'Copyright 2026 VolunteerX. All rights reserved.',
      'Create and manage events': 'Create and manage events',
      'Current Email': 'Current Email',
      'Current Password': 'Current Password',
      'Daily Schedules': 'Daily Schedules',
      'Description': 'Description',
      'Description is required': 'Description is required',
      'Developed By': 'Developed By',
      'Do you want to publish this draft event now?': 'Do you want to publish this draft event now?',
      'Draft saved': 'Draft saved',
      'Edit Draft': 'Edit Draft',
      'Edit Event': 'Edit Event',
      'End Date': 'End Date',
      'End Time': 'End Time',
      'Enter a valid 6-digit OTP': 'Enter a valid 6-digit OTP',
      'Enter a valid email': 'Enter a valid email',
      'Enter a valid phone number': 'Enter a valid phone number',
      'Enter new email address': 'Enter new email address',
      'Enter new password': 'Enter new password',
      'Enter organisation name': 'Enter organisation name',
      'Enter OTP': 'Enter OTP',
      'Enter phone number': 'Enter phone number',
      'Enter valid payment amount': 'Enter valid payment amount',
      'Enter valid volunteers required': 'Enter valid volunteers required',
      'Enter your password': 'Enter your password',
      'Event': 'Event',
      'Event Banner (Optional)': 'Event Banner (Optional)',
      'Event Cancelled': 'Event Cancelled',
      'Event cancelled successfully': 'Event cancelled successfully',
      'Event Chat': 'Event Chat',
      'Event Completed': 'Event Completed',
      'Event created': 'Event created',
      'Event Details': 'Event Details',
      'Event Info': 'Event Info',
      'Event Overview': 'Event Overview',
      'Event published': 'Event published',
      'Event published successfully': 'Event published successfully',
      'Event Title': 'Event Title',
      'Event title is required': 'Event title is required',
      'Event Type': 'Event Type',
      'Event updated': 'Event updated',
      'Event Updates': 'Event Updates',
      'Failed to create event': 'Failed to create event',
      'Failed to load applications. Please try again.': 'Failed to load applications. Please try again.',
      'Failed to load events': 'Failed to load events',
      'Failed to open chat': 'Failed to open chat',
      'Failed to save draft': 'Failed to save draft',
      'Failed to update application status.': 'Failed to update application status.',
      'Field cannot be empty': 'Field cannot be empty',
      'Fixed Amount': 'Fixed Amount',
      'Generate schedules from dates': 'Generate schedules from dates',
      'Government ID (Optional)': 'Government ID (Optional)',
      'Hire trusted volunteers': 'Hire trusted volunteers',
      'Invalid event id': 'Invalid event id',
      'Location': 'Location',
      'Location is required': 'Location is required',
      'Message is required': 'Message is required',
      'Name A-Z': 'Name A-Z',
      'New Email': 'New Email',
      'New Password': 'New Password',
      'New Volunteer Applications': 'New Volunteer Applications',
      'Newest': 'Newest',
      'No approved applications yet': 'No approved applications yet',
      'No badges yet': 'No badges yet',
      'No cancelled applications yet': 'No cancelled applications yet',
      'No pending applications yet': 'No pending applications yet',
      'No recent participation yet.': 'No recent participation yet.',
      'No rejected applications yet': 'No rejected applications yet',
      'No responsibilities added': 'No responsibilities added',
      'No waitlisted applications yet': 'No waitlisted applications yet',
      'Not provided': 'Not provided',
      'Not shortlisted': 'Not shortlisted',
      'Not sure': 'Not sure',
      'Oldest': 'Oldest',
      'Optional note': 'Optional note',
      'Organisation Details': 'Organisation Details',
      'Organisation Name': 'Organisation Name',
      'Organiser Verification': 'Organiser Verification',
      'OTP sent to your phone number': 'OTP sent to your phone number',
      'Our Mission': 'Our Mission',
      'Paid': 'Paid',
      'PAN Card': 'PAN Card',
      'Partially available': 'Partially available',
      'Passport': 'Passport',
      'Password': 'Password',
      'Password must be at least 6 characters': 'Password must be at least 6 characters',
      'Password updated successfully': 'Password updated successfully',
      'Passwords do not match': 'Passwords do not match',
      'Past Event Categories': 'Past Event Categories',
      'Payment Amount': 'Payment Amount',
      'Payment Clearance Date': 'Payment Clearance Date',
      'Payment clearance date cannot be before the event end date': 'Payment clearance date cannot be before the event end date',
      'Payment Rate': 'Payment Rate',
      'Pending / Waitlisted': 'Pending / Waitlisted',
      'Per Day': 'Per Day',
      'Per Hour': 'Per Hour',
      'Phone Number': 'Phone Number',
      'Phone number updated successfully': 'Phone number updated successfully',
      'Please provide cancellation reason': 'Please provide cancellation reason',
      'Preferences': 'Preferences',
      'Present': 'Present',
      'Promotional Notifications': 'Promotional Notifications',
      'Proof Selected': 'Proof Selected',
      'Publish': 'Publish',
      'Publish Event': 'Publish Event',
      'Rate Volunteer': 'Rate Volunteer',
      'Recent Participation': 'Recent Participation',
      'Removed from shortlist': 'Removed from shortlist',
      'Responsibilities': 'Responsibilities',
      'Review volunteer applications': 'Review volunteer applications',
      'Save Attendance': 'Save Attendance',
      'Save Draft': 'Save Draft',
      'Schedule': 'Schedule',
      'Select a cancellation reason': 'Select a cancellation reason',
      'Select application deadline': 'Select application deadline',
      'Select at least one category': 'Select at least one category',
      'Select event start and end dates': 'Select event start and end dates',
      'Select event start and end time': 'Select event start and end time',
      'Select payment clearance date': 'Select payment clearance date',
      'Select start and end dates first': 'Select start and end dates first',
      'Send': 'Send',
      'Send Announcement': 'Send Announcement',
      'Send OTP': 'Send OTP',
      'Sending...': 'Sending...',
      'Shortlist:': 'Shortlist:',
      'Shortlisted': 'Shortlisted',
      'Show contact number to volunteers': 'Show contact number to volunteers',
      'Start Date': 'Start Date',
      'Start Time': 'Start Time',
      'This action is irreversible. All data will be lost.': 'This action is irreversible. All data will be lost.',
      'This application can no longer be changed.': 'This application can no longer be changed.',
      'This application has been cancelled.': 'This application has been cancelled.',
      'This application is already approved.': 'This application is already approved.',
      'This application is already rejected.': 'This application is already rejected.',
      'This participation is already completed.': 'This participation is already completed.',
      'Token missing. Please login again.': 'Token missing. Please login again.',
      'Top badge: {badge}': 'Top badge: {badge}',
      'Track volunteer performance': 'Track volunteer performance',
      'Type announcement...': 'Type announcement...',
      'Unpaid': 'Unpaid',
      'Update Email': 'Update Email',
      'Update Event': 'Update Event',
      'Update failed': 'Update failed',
      'Update Password': 'Update Password',
      'Update Phone Number': 'Update Phone Number',
      'Upload Event Banner (Optional)': 'Upload Event Banner (Optional)',
      'Upload Event Proof / Certificate': 'Upload Event Proof / Certificate',
      'Verification email sent to new address': 'Verification email sent to new address',
      'Verify OTP': 'Verify OTP',
      'Version': 'Version',
      'View Application': 'View Application',
      'View Volunteers': 'View Volunteers',
    'Mark Attendance': 'उपस्थिति दर्ज करें',
      'volunteer': 'volunteer',
      'volunteers': 'volunteers',
      'Volunteers Required': 'Volunteers Required',
      'VolunteerX v1.0.0': 'VolunteerX v1.0.0',
      'Waitlisted': 'Waitlisted',
      'Website / Social Link': 'Website / Social Link',
      'What is VolunteerX?': 'What is VolunteerX?',
      'What You Can Do': 'What You Can Do',
      'Write a message for volunteers in this event.': 'Write a message for volunteers in this event.',
      'Write cancellation reason': 'Write cancellation reason',
      'Your account will be temporarily disabled.': 'Your account will be temporarily disabled.',
      'About this Event': 'About this Event',
      'Appeal approved': 'Appeal approved',
      'Appeal available': 'Appeal available',
      'Appeal pending': 'Appeal pending',
      'Appeal reason': 'Appeal reason',
      'Appeal rejected': 'Appeal rejected',
      'Application Approved': 'Application Approved',
      'Application Cancelled': 'Application Cancelled',
      'Application Pending': 'Application Pending',
      'Application Rejected': 'Application Rejected',
      'Application Status Updated': 'Application Status Updated',
      'Application Waitlisted': 'Application Waitlisted',
      'Applications closed': 'Applications closed',
      'Applied Events': 'Applied Events',
      'Apply for this Event': 'Apply for this Event',
      'Attendance Absent': 'Attendance Absent',
      'Attendance absent': 'Attendance absent',
      'Attendance present': 'Attendance present',
      'Availability for this event': 'Availability for this event',
      'Cancel Participation': 'Cancel Participation',
      'Cancel Participation (Locked)': 'Cancel Participation (Locked)',
      'Clear': 'Clear',
      'Close search': 'Close search',
      'Confirm & Apply': 'Confirm & Apply',
      'Confirm Cancel': 'Confirm Cancel',
    'Couldn\'t verify your account status. Please try again.': 'Couldn\'t verify your account status. Please try again.',
      'Date': 'Date',
      'Date not available': 'Date not available',
      'Document uploaded': 'Document uploaded',
      'Event cancelled': 'Event cancelled',
      'Event completed': 'Event completed',
      'Event not found': 'Event not found',
      'Event removed': 'Event removed',
      'Failed to load event details': 'Failed to load event details',
      'Failed to load saved events.': 'Failed to load saved events.',
      'Filter Events': 'Filter Events',
      'Filters': 'Filters',
      'fixed amount': 'fixed amount',
      'I agree to the Terms & Conditions': 'I agree to the Terms & Conditions',
      'Join on VolunteerX': 'Join on VolunteerX',
      'Keep': 'Keep',
      'No applications found': 'No applications found',
      'No document uploaded': 'No document uploaded',
      'No responsibilities provided by organiser.': 'No responsibilities provided by organiser.',
      'No saved events yet': 'No saved events yet',
      'No volunteer history yet': 'No volunteer history yet',
      'Open': 'Open',
      'Open Events': 'Open Events',
      'Organiser profile not available': 'Organiser profile not available',
      'Participation cancelled.': 'Participation cancelled.',
      'Participation cancelled. A strike was applied.': 'Participation cancelled. A strike was applied.',
      'Past': 'Past',
      'per day': 'per day',
      'per hour': 'per hour',
      'Prior Experience (optional)': 'Prior Experience (optional)',
      'Rate organiser': 'Rate organiser',
      'Rate Organiser': 'Rate Organiser',
      'Reason (optional but recommended)': 'Reason (optional but recommended)',
      'Reason *': 'Reason *',
      'Reason is mandatory within 48 hours': 'Reason is mandatory within 48 hours',
      'Remove from saved': 'Remove from saved',
      'Removed from saved': 'Removed from saved',
      'Save event': 'Save event',
      'Saved event': 'Saved event',
      'Search': 'Search',
      'Strike appeal submitted': 'Strike appeal submitted',
      'Strike applied': 'Strike applied',
      'Submit Appeal': 'Submit Appeal',
      'Submit appeal': 'Submit appeal',
      'Submit Strike Appeal': 'Submit Strike Appeal',
      'Supporting document': 'Supporting document',
      'Supporting document *': 'Supporting document *',
      'This application was cancelled.': 'This application was cancelled.',
      'This application was not approved.': 'This application was not approved.',
      'This event ended before your application was reviewed.':
          'à¤†à¤ªà¤•à¥‡ à¤†à¤µà¥‡à¤¦à¤¨ à¤•à¥€ à¤¸à¤®à¥€à¤•à¥à¤·à¤¾ à¤¹à¥‹à¤¨à¥‡ à¤¸à¥‡ à¤ªà¤¹à¤²à¥‡ à¤¯à¤¹ à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤® à¤¸à¤®à¤¾à¤ªà¥à¤¤ à¤¹à¥‹ à¤—à¤¯à¤¾à¥¤',
      'This event ended before this application could be reviewed.':
          'à¤‡à¤¸ à¤†à¤µà¥‡à¤¦à¤¨ à¤•à¥€ à¤¸à¤®à¥€à¤•à¥à¤·à¤¾ à¤¹à¥‹à¤¨à¥‡ à¤¸à¥‡ à¤ªà¤¹à¤²à¥‡ à¤¯à¤¹ à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤® à¤¸à¤®à¤¾à¤ªà¥à¤¤ à¤¹à¥‹ à¤—à¤¯à¤¾à¥¤',
      'Unable to apply': 'Unable to apply',
      'Upload': 'Upload',
      'Verification Required': 'Verification Required',
      'Verification required to apply': 'Verification required to apply',
      'View organiser profile': 'View organiser profile',
      'Volunteer Terms & Conditions': 'Volunteer Terms & Conditions',
      'Warning issued': 'Warning issued',
      'You are confirmed for this event.': 'You are confirmed for this event.',
      'You were marked absent for this event.': 'You were marked absent for this event.',
      'Your application is under review.': 'Your application is under review.',
      'Your attendance was marked present for this event.': 'Your attendance was marked present for this event.',
      'Your participation for this event is completed.': 'Your participation for this event is completed.',
      'Your Responsibilities': 'Your Responsibilities',
    },
  };

  String t(String key, {Map<String, String> args = const {}}) {
    final lang = _localizedValues[locale.languageCode] ??
        _localizedValues['en'] ??
        const {};
    var value = lang[key] ?? _localizedValues['en']?[key] ?? key;
    if (args.isNotEmpty) {
      args.forEach((k, v) {
        value = value.replaceAll('{$k}', v);
      });
    }
    return value;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales
        .any((supported) => supported.languageCode == locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}



